apiVersion: 1

datasources:
  # Prometheus
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: POST

  # Jaeger
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: true
    jsonData:
      tracesToLogs:
        datasourceUid: 'loki'
        tags: ['job', 'instance', 'pod', 'namespace']
        mappedTags: [{ key: 'service.name', value: 'service' }]
        mapTagNamesEnabled: false
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: false
        filterBySpanID: false

  # Postgres (for debugging)
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: schlep_engine
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
    editable: true
