apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "schlep-engine.fullname" . }}-config
  labels:
    {{- include "schlep-engine.labels" . | nindent 4 }}
data:
  {{- if .Values.configMaps.cacheTopology.enabled }}
  {{- range $key, $value := .Values.configMaps.cacheTopology.data }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
  {{- end }}
