{{- if .Values.persistence.modelStorage.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "igris-inertial.fullname" . }}-models
  labels:
    {{- include "igris-inertial.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.modelStorage.accessMode }}
  {{- if .Values.persistence.modelStorage.storageClass }}
  storageClassName: {{ .Values.persistence.modelStorage.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.modelStorage.size }}
{{- end }}
---
{{- if .Values.persistence.dataStorage.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "igris-inertial.fullname" . }}-data
  labels:
    {{- include "igris-inertial.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.dataStorage.accessMode }}
  {{- if .Values.persistence.dataStorage.storageClass }}
  storageClassName: {{ .Values.persistence.dataStorage.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.dataStorage.size }}
{{- end }}
