"""Re-generate: Add fields to DataInvestigation and ProcessingJob

Revision ID: b4666f8be3af
Revises: 51eb2357e1f2
Create Date: 2025-05-31 19:01:23.779542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4666f8be3af'
down_revision: Union[str, None] = '51eb2357e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_investigations', sa.Column('original_file_path', sa.String(), nullable=True))
    op.add_column('data_investigations', sa.Column('processed_file_path', sa.String(), nullable=True))
    op.add_column('processing_jobs', sa.Column('output_summary', sa.JSON(), nullable=True))
    op.add_column('processing_jobs', sa.Column('output_artifact_path', sa.String(), nullable=True))
    op.drop_column('processing_jobs', 'result')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_jobs', sa.Column('result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('processing_jobs', 'output_artifact_path')
    op.drop_column('processing_jobs', 'output_summary')
    op.drop_column('data_investigations', 'processed_file_path')
    op.drop_column('data_investigations', 'original_file_path')
    # ### end Alembic commands ###
