apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: schlep-engine-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: schlep-engine-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: prod/schlep-engine/database-url
    - secretKey: REDIS_URL
      remoteRef:
        key: prod/schlep-engine/redis-url
    - secretKey: SECRET_KEY
      remoteRef:
        key: prod/schlep-engine/secret-key 