// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: labs/proto/orchestration/inference_router.proto

package orchestration

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InferenceRouterService_RouteInference_FullMethodName      = "/orchestration.InferenceRouterService/RouteInference"
	InferenceRouterService_RouteBatchInference_FullMethodName = "/orchestration.InferenceRouterService/RouteBatchInference"
	InferenceRouterService_CreatePolicy_FullMethodName        = "/orchestration.InferenceRouterService/CreatePolicy"
	InferenceRouterService_UpdatePolicy_FullMethodName        = "/orchestration.InferenceRouterService/UpdatePolicy"
	InferenceRouterService_DeletePolicy_FullMethodName        = "/orchestration.InferenceRouterService/DeletePolicy"
	InferenceRouterService_GetPolicy_FullMethodName           = "/orchestration.InferenceRouterService/GetPolicy"
	InferenceRouterService_ListPolicies_FullMethodName        = "/orchestration.InferenceRouterService/ListPolicies"
	InferenceRouterService_RegisterModel_FullMethodName       = "/orchestration.InferenceRouterService/RegisterModel"
	InferenceRouterService_UpdateModelInfo_FullMethodName     = "/orchestration.InferenceRouterService/UpdateModelInfo"
	InferenceRouterService_GetModelInfo_FullMethodName        = "/orchestration.InferenceRouterService/GetModelInfo"
	InferenceRouterService_ListModels_FullMethodName          = "/orchestration.InferenceRouterService/ListModels"
	InferenceRouterService_HealthCheck_FullMethodName         = "/orchestration.InferenceRouterService/HealthCheck"
	InferenceRouterService_GetMetrics_FullMethodName          = "/orchestration.InferenceRouterService/GetMetrics"
	InferenceRouterService_GetRoutingStats_FullMethodName     = "/orchestration.InferenceRouterService/GetRoutingStats"
)

// InferenceRouterServiceClient is the client API for InferenceRouterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InferenceRouterServiceClient interface {
	// Core routing API
	RouteInference(ctx context.Context, in *RouteInferenceRequest, opts ...grpc.CallOption) (*RouteInferenceResponse, error)
	// Batch routing
	RouteBatchInference(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RouteInferenceRequest, RouteInferenceResponse], error)
	// Policy management
	CreatePolicy(ctx context.Context, in *CreatePolicyRequest, opts ...grpc.CallOption) (*CreatePolicyResponse, error)
	UpdatePolicy(ctx context.Context, in *UpdatePolicyRequest, opts ...grpc.CallOption) (*UpdatePolicyResponse, error)
	DeletePolicy(ctx context.Context, in *DeletePolicyRequest, opts ...grpc.CallOption) (*DeletePolicyResponse, error)
	GetPolicy(ctx context.Context, in *GetPolicyRequest, opts ...grpc.CallOption) (*GetPolicyResponse, error)
	ListPolicies(ctx context.Context, in *ListPoliciesRequest, opts ...grpc.CallOption) (*ListPoliciesResponse, error)
	// Model registry integration
	RegisterModel(ctx context.Context, in *RegisterModelRequest, opts ...grpc.CallOption) (*RegisterModelResponse, error)
	UpdateModelInfo(ctx context.Context, in *UpdateModelInfoRequest, opts ...grpc.CallOption) (*UpdateModelInfoResponse, error)
	GetModelInfo(ctx context.Context, in *GetModelInfoRequest, opts ...grpc.CallOption) (*GetModelInfoResponse, error)
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	// Health and metrics
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	GetMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error)
	GetRoutingStats(ctx context.Context, in *RoutingStatsRequest, opts ...grpc.CallOption) (*RoutingStatsResponse, error)
}

type inferenceRouterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInferenceRouterServiceClient(cc grpc.ClientConnInterface) InferenceRouterServiceClient {
	return &inferenceRouterServiceClient{cc}
}

func (c *inferenceRouterServiceClient) RouteInference(ctx context.Context, in *RouteInferenceRequest, opts ...grpc.CallOption) (*RouteInferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteInferenceResponse)
	err := c.cc.Invoke(ctx, InferenceRouterService_RouteInference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceRouterServiceClient) RouteBatchInference(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RouteInferenceRequest, RouteInferenceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InferenceRouterService_ServiceDesc.Streams[0], InferenceRouterService_RouteBatchInference_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RouteInferenceRequest, RouteInferenceResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InferenceRouterService_RouteBatchInferenceClient = grpc.BidiStreamingClient[RouteInferenceRequest, RouteInferenceResponse]

func (c *inferenceRouterServiceClient) CreatePolicy(ctx context.Context, in *CreatePolicyRequest, opts ...grpc.CallOption) (*CreatePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePolicyResponse)
	err := c.cc.Invoke(ctx, InferenceRouterService_CreatePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceRouterServiceClient) UpdatePolicy(ctx context.Context, in *UpdatePolicyRequest, opts ...grpc.CallOption) (*UpdatePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePolicyResponse)
	err := c.cc.Invoke(ctx, InferenceRouterService_UpdatePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceRouterServiceClient) DeletePolicy(ctx context.Context, in *DeletePolicyRequest, opts ...grpc.CallOption) (*DeletePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePolicyResponse)
	err := c.cc.Invoke(ctx, InferenceRouterService_DeletePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceRouterServiceClient) GetPolicy(ctx context.Context, in *GetPolicyRequest, opts ...grpc.CallOption) (*GetPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPolicyResponse)
	err := c.cc.Invoke(ctx, InferenceRouterService_GetPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceRouterServiceClient) ListPolicies(ctx context.Context, in *ListPoliciesRequest, opts ...grpc.CallOption) (*ListPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPoliciesResponse)
	err := c.cc.Invoke(ctx, InferenceRouterService_ListPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceRouterServiceClient) RegisterModel(ctx context.Context, in *RegisterModelRequest, opts ...grpc.CallOption) (*RegisterModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterModelResponse)
	err := c.cc.Invoke(ctx, InferenceRouterService_RegisterModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceRouterServiceClient) UpdateModelInfo(ctx context.Context, in *UpdateModelInfoRequest, opts ...grpc.CallOption) (*UpdateModelInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateModelInfoResponse)
	err := c.cc.Invoke(ctx, InferenceRouterService_UpdateModelInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceRouterServiceClient) GetModelInfo(ctx context.Context, in *GetModelInfoRequest, opts ...grpc.CallOption) (*GetModelInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModelInfoResponse)
	err := c.cc.Invoke(ctx, InferenceRouterService_GetModelInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceRouterServiceClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, InferenceRouterService_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceRouterServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, InferenceRouterService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceRouterServiceClient) GetMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetricsResponse)
	err := c.cc.Invoke(ctx, InferenceRouterService_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceRouterServiceClient) GetRoutingStats(ctx context.Context, in *RoutingStatsRequest, opts ...grpc.CallOption) (*RoutingStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoutingStatsResponse)
	err := c.cc.Invoke(ctx, InferenceRouterService_GetRoutingStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InferenceRouterServiceServer is the server API for InferenceRouterService service.
// All implementations must embed UnimplementedInferenceRouterServiceServer
// for forward compatibility.
type InferenceRouterServiceServer interface {
	// Core routing API
	RouteInference(context.Context, *RouteInferenceRequest) (*RouteInferenceResponse, error)
	// Batch routing
	RouteBatchInference(grpc.BidiStreamingServer[RouteInferenceRequest, RouteInferenceResponse]) error
	// Policy management
	CreatePolicy(context.Context, *CreatePolicyRequest) (*CreatePolicyResponse, error)
	UpdatePolicy(context.Context, *UpdatePolicyRequest) (*UpdatePolicyResponse, error)
	DeletePolicy(context.Context, *DeletePolicyRequest) (*DeletePolicyResponse, error)
	GetPolicy(context.Context, *GetPolicyRequest) (*GetPolicyResponse, error)
	ListPolicies(context.Context, *ListPoliciesRequest) (*ListPoliciesResponse, error)
	// Model registry integration
	RegisterModel(context.Context, *RegisterModelRequest) (*RegisterModelResponse, error)
	UpdateModelInfo(context.Context, *UpdateModelInfoRequest) (*UpdateModelInfoResponse, error)
	GetModelInfo(context.Context, *GetModelInfoRequest) (*GetModelInfoResponse, error)
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	// Health and metrics
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	GetMetrics(context.Context, *MetricsRequest) (*MetricsResponse, error)
	GetRoutingStats(context.Context, *RoutingStatsRequest) (*RoutingStatsResponse, error)
	mustEmbedUnimplementedInferenceRouterServiceServer()
}

// UnimplementedInferenceRouterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferenceRouterServiceServer struct{}

func (UnimplementedInferenceRouterServiceServer) RouteInference(context.Context, *RouteInferenceRequest) (*RouteInferenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RouteInference not implemented")
}
func (UnimplementedInferenceRouterServiceServer) RouteBatchInference(grpc.BidiStreamingServer[RouteInferenceRequest, RouteInferenceResponse]) error {
	return status.Errorf(codes.Unimplemented, "method RouteBatchInference not implemented")
}
func (UnimplementedInferenceRouterServiceServer) CreatePolicy(context.Context, *CreatePolicyRequest) (*CreatePolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePolicy not implemented")
}
func (UnimplementedInferenceRouterServiceServer) UpdatePolicy(context.Context, *UpdatePolicyRequest) (*UpdatePolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePolicy not implemented")
}
func (UnimplementedInferenceRouterServiceServer) DeletePolicy(context.Context, *DeletePolicyRequest) (*DeletePolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePolicy not implemented")
}
func (UnimplementedInferenceRouterServiceServer) GetPolicy(context.Context, *GetPolicyRequest) (*GetPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPolicy not implemented")
}
func (UnimplementedInferenceRouterServiceServer) ListPolicies(context.Context, *ListPoliciesRequest) (*ListPoliciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPolicies not implemented")
}
func (UnimplementedInferenceRouterServiceServer) RegisterModel(context.Context, *RegisterModelRequest) (*RegisterModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterModel not implemented")
}
func (UnimplementedInferenceRouterServiceServer) UpdateModelInfo(context.Context, *UpdateModelInfoRequest) (*UpdateModelInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateModelInfo not implemented")
}
func (UnimplementedInferenceRouterServiceServer) GetModelInfo(context.Context, *GetModelInfoRequest) (*GetModelInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModelInfo not implemented")
}
func (UnimplementedInferenceRouterServiceServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedInferenceRouterServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedInferenceRouterServiceServer) GetMetrics(context.Context, *MetricsRequest) (*MetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedInferenceRouterServiceServer) GetRoutingStats(context.Context, *RoutingStatsRequest) (*RoutingStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoutingStats not implemented")
}
func (UnimplementedInferenceRouterServiceServer) mustEmbedUnimplementedInferenceRouterServiceServer() {
}
func (UnimplementedInferenceRouterServiceServer) testEmbeddedByValue() {}

// UnsafeInferenceRouterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferenceRouterServiceServer will
// result in compilation errors.
type UnsafeInferenceRouterServiceServer interface {
	mustEmbedUnimplementedInferenceRouterServiceServer()
}

func RegisterInferenceRouterServiceServer(s grpc.ServiceRegistrar, srv InferenceRouterServiceServer) {
	// If the following call pancis, it indicates UnimplementedInferenceRouterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InferenceRouterService_ServiceDesc, srv)
}

func _InferenceRouterService_RouteInference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteInferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceRouterServiceServer).RouteInference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceRouterService_RouteInference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceRouterServiceServer).RouteInference(ctx, req.(*RouteInferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceRouterService_RouteBatchInference_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InferenceRouterServiceServer).RouteBatchInference(&grpc.GenericServerStream[RouteInferenceRequest, RouteInferenceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InferenceRouterService_RouteBatchInferenceServer = grpc.BidiStreamingServer[RouteInferenceRequest, RouteInferenceResponse]

func _InferenceRouterService_CreatePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceRouterServiceServer).CreatePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceRouterService_CreatePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceRouterServiceServer).CreatePolicy(ctx, req.(*CreatePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceRouterService_UpdatePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceRouterServiceServer).UpdatePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceRouterService_UpdatePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceRouterServiceServer).UpdatePolicy(ctx, req.(*UpdatePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceRouterService_DeletePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceRouterServiceServer).DeletePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceRouterService_DeletePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceRouterServiceServer).DeletePolicy(ctx, req.(*DeletePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceRouterService_GetPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceRouterServiceServer).GetPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceRouterService_GetPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceRouterServiceServer).GetPolicy(ctx, req.(*GetPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceRouterService_ListPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceRouterServiceServer).ListPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceRouterService_ListPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceRouterServiceServer).ListPolicies(ctx, req.(*ListPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceRouterService_RegisterModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceRouterServiceServer).RegisterModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceRouterService_RegisterModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceRouterServiceServer).RegisterModel(ctx, req.(*RegisterModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceRouterService_UpdateModelInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateModelInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceRouterServiceServer).UpdateModelInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceRouterService_UpdateModelInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceRouterServiceServer).UpdateModelInfo(ctx, req.(*UpdateModelInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceRouterService_GetModelInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceRouterServiceServer).GetModelInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceRouterService_GetModelInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceRouterServiceServer).GetModelInfo(ctx, req.(*GetModelInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceRouterService_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceRouterServiceServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceRouterService_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceRouterServiceServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceRouterService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceRouterServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceRouterService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceRouterServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceRouterService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceRouterServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceRouterService_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceRouterServiceServer).GetMetrics(ctx, req.(*MetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceRouterService_GetRoutingStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoutingStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceRouterServiceServer).GetRoutingStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceRouterService_GetRoutingStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceRouterServiceServer).GetRoutingStats(ctx, req.(*RoutingStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InferenceRouterService_ServiceDesc is the grpc.ServiceDesc for InferenceRouterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InferenceRouterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orchestration.InferenceRouterService",
	HandlerType: (*InferenceRouterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RouteInference",
			Handler:    _InferenceRouterService_RouteInference_Handler,
		},
		{
			MethodName: "CreatePolicy",
			Handler:    _InferenceRouterService_CreatePolicy_Handler,
		},
		{
			MethodName: "UpdatePolicy",
			Handler:    _InferenceRouterService_UpdatePolicy_Handler,
		},
		{
			MethodName: "DeletePolicy",
			Handler:    _InferenceRouterService_DeletePolicy_Handler,
		},
		{
			MethodName: "GetPolicy",
			Handler:    _InferenceRouterService_GetPolicy_Handler,
		},
		{
			MethodName: "ListPolicies",
			Handler:    _InferenceRouterService_ListPolicies_Handler,
		},
		{
			MethodName: "RegisterModel",
			Handler:    _InferenceRouterService_RegisterModel_Handler,
		},
		{
			MethodName: "UpdateModelInfo",
			Handler:    _InferenceRouterService_UpdateModelInfo_Handler,
		},
		{
			MethodName: "GetModelInfo",
			Handler:    _InferenceRouterService_GetModelInfo_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _InferenceRouterService_ListModels_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _InferenceRouterService_HealthCheck_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _InferenceRouterService_GetMetrics_Handler,
		},
		{
			MethodName: "GetRoutingStats",
			Handler:    _InferenceRouterService_GetRoutingStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RouteBatchInference",
			Handler:       _InferenceRouterService_RouteBatchInference_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "labs/proto/orchestration/inference_router.proto",
}

const (
	InferenceExecutionService_ExecuteInference_FullMethodName = "/orchestration.InferenceExecutionService/ExecuteInference"
	InferenceExecutionService_ExecuteBatch_FullMethodName     = "/orchestration.InferenceExecutionService/ExecuteBatch"
)

// InferenceExecutionServiceClient is the client API for InferenceExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InferenceExecutionServiceClient interface {
	// Execute inference (after routing)
	ExecuteInference(ctx context.Context, in *InferenceRequest, opts ...grpc.CallOption) (*InferenceResponse, error)
	// Batch execution
	ExecuteBatch(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InferenceRequest, InferenceResponse], error)
}

type inferenceExecutionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInferenceExecutionServiceClient(cc grpc.ClientConnInterface) InferenceExecutionServiceClient {
	return &inferenceExecutionServiceClient{cc}
}

func (c *inferenceExecutionServiceClient) ExecuteInference(ctx context.Context, in *InferenceRequest, opts ...grpc.CallOption) (*InferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InferenceResponse)
	err := c.cc.Invoke(ctx, InferenceExecutionService_ExecuteInference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceExecutionServiceClient) ExecuteBatch(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InferenceRequest, InferenceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InferenceExecutionService_ServiceDesc.Streams[0], InferenceExecutionService_ExecuteBatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InferenceRequest, InferenceResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InferenceExecutionService_ExecuteBatchClient = grpc.BidiStreamingClient[InferenceRequest, InferenceResponse]

// InferenceExecutionServiceServer is the server API for InferenceExecutionService service.
// All implementations must embed UnimplementedInferenceExecutionServiceServer
// for forward compatibility.
type InferenceExecutionServiceServer interface {
	// Execute inference (after routing)
	ExecuteInference(context.Context, *InferenceRequest) (*InferenceResponse, error)
	// Batch execution
	ExecuteBatch(grpc.BidiStreamingServer[InferenceRequest, InferenceResponse]) error
	mustEmbedUnimplementedInferenceExecutionServiceServer()
}

// UnimplementedInferenceExecutionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferenceExecutionServiceServer struct{}

func (UnimplementedInferenceExecutionServiceServer) ExecuteInference(context.Context, *InferenceRequest) (*InferenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteInference not implemented")
}
func (UnimplementedInferenceExecutionServiceServer) ExecuteBatch(grpc.BidiStreamingServer[InferenceRequest, InferenceResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ExecuteBatch not implemented")
}
func (UnimplementedInferenceExecutionServiceServer) mustEmbedUnimplementedInferenceExecutionServiceServer() {
}
func (UnimplementedInferenceExecutionServiceServer) testEmbeddedByValue() {}

// UnsafeInferenceExecutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferenceExecutionServiceServer will
// result in compilation errors.
type UnsafeInferenceExecutionServiceServer interface {
	mustEmbedUnimplementedInferenceExecutionServiceServer()
}

func RegisterInferenceExecutionServiceServer(s grpc.ServiceRegistrar, srv InferenceExecutionServiceServer) {
	// If the following call pancis, it indicates UnimplementedInferenceExecutionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InferenceExecutionService_ServiceDesc, srv)
}

func _InferenceExecutionService_ExecuteInference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceExecutionServiceServer).ExecuteInference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceExecutionService_ExecuteInference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceExecutionServiceServer).ExecuteInference(ctx, req.(*InferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceExecutionService_ExecuteBatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InferenceExecutionServiceServer).ExecuteBatch(&grpc.GenericServerStream[InferenceRequest, InferenceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InferenceExecutionService_ExecuteBatchServer = grpc.BidiStreamingServer[InferenceRequest, InferenceResponse]

// InferenceExecutionService_ServiceDesc is the grpc.ServiceDesc for InferenceExecutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InferenceExecutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orchestration.InferenceExecutionService",
	HandlerType: (*InferenceExecutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteInference",
			Handler:    _InferenceExecutionService_ExecuteInference_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteBatch",
			Handler:       _InferenceExecutionService_ExecuteBatch_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "labs/proto/orchestration/inference_router.proto",
}
