// @ts-nocheck
import * as __fd_glob_68 from "../content/docs/articles/thompson-sampling-routing.mdx?collection=docs"
import * as __fd_glob_67 from "../content/docs/articles/safe-agents-capability-gates.mdx?collection=docs"
import * as __fd_glob_66 from "../content/docs/articles/index.mdx?collection=docs"
import * as __fd_glob_65 from "../content/docs/articles/edge-deployment-guide.mdx?collection=docs"
import * as __fd_glob_64 from "../content/docs/webhooks.mdx?collection=docs"
import * as __fd_glob_63 from "../content/docs/upgrade-migration.mdx?collection=docs"
import * as __fd_glob_62 from "../content/docs/troubleshooting.mdx?collection=docs"
import * as __fd_glob_61 from "../content/docs/trial-billing.mdx?collection=docs"
import * as __fd_glob_60 from "../content/docs/tools.mdx?collection=docs"
import * as __fd_glob_59 from "../content/docs/tamper-evident-logs.mdx?collection=docs"
import * as __fd_glob_58 from "../content/docs/swarm.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/speculative-execution.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/slo-enforcer.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/sla.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/shadow-mode.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/security.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/sdk.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/sdk-integration-patterns.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/safety.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/ros2-integration.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/robotics.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/receipts-audit-workflow.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/rate-limiting.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/quickstart.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/provider-health.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/pricing-tiers.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/policy.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/multimodal.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/multi-tenancy.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/model-aggregation.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/memory.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/mcp.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/mcp-swarm.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/mcp-server.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/mcp-integration-patterns.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/local-llm-fallback.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/key-management.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/index.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/hybrid-deployment-workflow.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/history.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/governance.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/fleet-rollout-workflow.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/fleet-management.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/first-cloud-integration.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/execution-receipts.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/execution-model.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/execution-flow.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/escapevector.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/error-codes.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/durable-tasks.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/documentation-roadmap.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/deployment.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/deploy-local-runtime.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/data-privacy.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/context-engineering.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/console.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/cognitive-advisor.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/cloud-coordination.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/circuit-breaker.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/changelog.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/capability-model.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/behavior-trees.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/audit.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/architecture.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/approval-workflows.mdx?collection=docs"
import * as __fd_glob_3 from "../content/docs/api-reference.mdx?collection=docs"
import * as __fd_glob_2 from "../content/docs/agents.mdx?collection=docs"
import * as __fd_glob_1 from "../content/docs/agent-lifecycle.mdx?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, }, {"agent-lifecycle.mdx": __fd_glob_1, "agents.mdx": __fd_glob_2, "api-reference.mdx": __fd_glob_3, "approval-workflows.mdx": __fd_glob_4, "architecture.mdx": __fd_glob_5, "audit.mdx": __fd_glob_6, "behavior-trees.mdx": __fd_glob_7, "capability-model.mdx": __fd_glob_8, "changelog.mdx": __fd_glob_9, "circuit-breaker.mdx": __fd_glob_10, "cloud-coordination.mdx": __fd_glob_11, "cognitive-advisor.mdx": __fd_glob_12, "console.mdx": __fd_glob_13, "context-engineering.mdx": __fd_glob_14, "data-privacy.mdx": __fd_glob_15, "deploy-local-runtime.mdx": __fd_glob_16, "deployment.mdx": __fd_glob_17, "documentation-roadmap.mdx": __fd_glob_18, "durable-tasks.mdx": __fd_glob_19, "error-codes.mdx": __fd_glob_20, "escapevector.mdx": __fd_glob_21, "execution-flow.mdx": __fd_glob_22, "execution-model.mdx": __fd_glob_23, "execution-receipts.mdx": __fd_glob_24, "first-cloud-integration.mdx": __fd_glob_25, "fleet-management.mdx": __fd_glob_26, "fleet-rollout-workflow.mdx": __fd_glob_27, "governance.mdx": __fd_glob_28, "history.mdx": __fd_glob_29, "hybrid-deployment-workflow.mdx": __fd_glob_30, "index.mdx": __fd_glob_31, "key-management.mdx": __fd_glob_32, "local-llm-fallback.mdx": __fd_glob_33, "mcp-integration-patterns.mdx": __fd_glob_34, "mcp-server.mdx": __fd_glob_35, "mcp-swarm.mdx": __fd_glob_36, "mcp.mdx": __fd_glob_37, "memory.mdx": __fd_glob_38, "model-aggregation.mdx": __fd_glob_39, "multi-tenancy.mdx": __fd_glob_40, "multimodal.mdx": __fd_glob_41, "policy.mdx": __fd_glob_42, "pricing-tiers.mdx": __fd_glob_43, "provider-health.mdx": __fd_glob_44, "quickstart.mdx": __fd_glob_45, "rate-limiting.mdx": __fd_glob_46, "receipts-audit-workflow.mdx": __fd_glob_47, "robotics.mdx": __fd_glob_48, "ros2-integration.mdx": __fd_glob_49, "safety.mdx": __fd_glob_50, "sdk-integration-patterns.mdx": __fd_glob_51, "sdk.mdx": __fd_glob_52, "security.mdx": __fd_glob_53, "shadow-mode.mdx": __fd_glob_54, "sla.mdx": __fd_glob_55, "slo-enforcer.mdx": __fd_glob_56, "speculative-execution.mdx": __fd_glob_57, "swarm.mdx": __fd_glob_58, "tamper-evident-logs.mdx": __fd_glob_59, "tools.mdx": __fd_glob_60, "trial-billing.mdx": __fd_glob_61, "troubleshooting.mdx": __fd_glob_62, "upgrade-migration.mdx": __fd_glob_63, "webhooks.mdx": __fd_glob_64, "articles/edge-deployment-guide.mdx": __fd_glob_65, "articles/index.mdx": __fd_glob_66, "articles/safe-agents-capability-gates.mdx": __fd_glob_67, "articles/thompson-sampling-routing.mdx": __fd_glob_68, });