// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: web/apps/python-ml-service/proto/ml_service.proto

package ml

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request messages
type PredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Features      []float64              `protobuf:"fixed64,2,rep,packed,name=features,proto3" json:"features,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutMs     int32                  `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_web_apps_python_ml_service_proto_ml_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_apps_python_ml_service_proto_ml_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_web_apps_python_ml_service_proto_ml_service_proto_rawDescGZIP(), []int{0}
}

func (x *PredictRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *PredictRequest) GetFeatures() []float64 {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *PredictRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PredictRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type BatchPredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	FeatureSets   []*FeatureSet          `protobuf:"bytes,2,rep,name=feature_sets,json=featureSets,proto3" json:"feature_sets,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutMs     int32                  `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPredictRequest) Reset() {
	*x = BatchPredictRequest{}
	mi := &file_web_apps_python_ml_service_proto_ml_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPredictRequest) ProtoMessage() {}

func (x *BatchPredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_apps_python_ml_service_proto_ml_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPredictRequest.ProtoReflect.Descriptor instead.
func (*BatchPredictRequest) Descriptor() ([]byte, []int) {
	return file_web_apps_python_ml_service_proto_ml_service_proto_rawDescGZIP(), []int{1}
}

func (x *BatchPredictRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *BatchPredictRequest) GetFeatureSets() []*FeatureSet {
	if x != nil {
		return x.FeatureSets
	}
	return nil
}

func (x *BatchPredictRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *BatchPredictRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type FeatureSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Features      []float64              `protobuf:"fixed64,1,rep,packed,name=features,proto3" json:"features,omitempty"`
	Identifier    string                 `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureSet) Reset() {
	*x = FeatureSet{}
	mi := &file_web_apps_python_ml_service_proto_ml_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureSet) ProtoMessage() {}

func (x *FeatureSet) ProtoReflect() protoreflect.Message {
	mi := &file_web_apps_python_ml_service_proto_ml_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureSet.ProtoReflect.Descriptor instead.
func (*FeatureSet) Descriptor() ([]byte, []int) {
	return file_web_apps_python_ml_service_proto_ml_service_proto_rawDescGZIP(), []int{2}
}

func (x *FeatureSet) GetFeatures() []float64 {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *FeatureSet) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detailed      bool                   `protobuf:"varint,1,opt,name=detailed,proto3" json:"detailed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_web_apps_python_ml_service_proto_ml_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_apps_python_ml_service_proto_ml_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_web_apps_python_ml_service_proto_ml_service_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckRequest) GetDetailed() bool {
	if x != nil {
		return x.Detailed
	}
	return false
}

type ModelInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfoRequest) Reset() {
	*x = ModelInfoRequest{}
	mi := &file_web_apps_python_ml_service_proto_ml_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfoRequest) ProtoMessage() {}

func (x *ModelInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_apps_python_ml_service_proto_ml_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfoRequest.ProtoReflect.Descriptor instead.
func (*ModelInfoRequest) Descriptor() ([]byte, []int) {
	return file_web_apps_python_ml_service_proto_ml_service_proto_rawDescGZIP(), []int{4}
}

func (x *ModelInfoRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type LoadModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ModelPath     string                 `protobuf:"bytes,2,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"`
	Config        map[string]string      `protobuf:"bytes,3,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadModelRequest) Reset() {
	*x = LoadModelRequest{}
	mi := &file_web_apps_python_ml_service_proto_ml_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModelRequest) ProtoMessage() {}

func (x *LoadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_apps_python_ml_service_proto_ml_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModelRequest.ProtoReflect.Descriptor instead.
func (*LoadModelRequest) Descriptor() ([]byte, []int) {
	return file_web_apps_python_ml_service_proto_ml_service_proto_rawDescGZIP(), []int{5}
}

func (x *LoadModelRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *LoadModelRequest) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

func (x *LoadModelRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type UnloadModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadModelRequest) Reset() {
	*x = UnloadModelRequest{}
	mi := &file_web_apps_python_ml_service_proto_ml_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadModelRequest) ProtoMessage() {}

func (x *UnloadModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_apps_python_ml_service_proto_ml_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadModelRequest.ProtoReflect.Descriptor instead.
func (*UnloadModelRequest) Descriptor() ([]byte, []int) {
	return file_web_apps_python_ml_service_proto_ml_service_proto_rawDescGZIP(), []int{6}
}

func (x *UnloadModelRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

// Response messages
type PredictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prediction    float64                `protobuf:"fixed64,1,opt,name=prediction,proto3" json:"prediction,omitempty"`
	Confidence    float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ModelId       string                 `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Probabilities map[string]float64     `protobuf:"bytes,5,rep,name=probabilities,proto3" json:"probabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_web_apps_python_ml_service_proto_ml_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_apps_python_ml_service_proto_ml_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_web_apps_python_ml_service_proto_ml_service_proto_rawDescGZIP(), []int{7}
}

func (x *PredictResponse) GetPrediction() float64 {
	if x != nil {
		return x.Prediction
	}
	return 0
}

func (x *PredictResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *PredictResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *PredictResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *PredictResponse) GetProbabilities() map[string]float64 {
	if x != nil {
		return x.Probabilities
	}
	return nil
}

func (x *PredictResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BatchPredictResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Predictions    []*PredictResponse     `protobuf:"bytes,1,rep,name=predictions,proto3" json:"predictions,omitempty"`
	TotalLatencyMs int64                  `protobuf:"varint,2,opt,name=total_latency_ms,json=totalLatencyMs,proto3" json:"total_latency_ms,omitempty"`
	SuccessCount   int32                  `protobuf:"varint,3,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	ErrorCount     int32                  `protobuf:"varint,4,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchPredictResponse) Reset() {
	*x = BatchPredictResponse{}
	mi := &file_web_apps_python_ml_service_proto_ml_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPredictResponse) ProtoMessage() {}

func (x *BatchPredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_apps_python_ml_service_proto_ml_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPredictResponse.ProtoReflect.Descriptor instead.
func (*BatchPredictResponse) Descriptor() ([]byte, []int) {
	return file_web_apps_python_ml_service_proto_ml_service_proto_rawDescGZIP(), []int{8}
}

func (x *BatchPredictResponse) GetPredictions() []*PredictResponse {
	if x != nil {
		return x.Predictions
	}
	return nil
}

func (x *BatchPredictResponse) GetTotalLatencyMs() int64 {
	if x != nil {
		return x.TotalLatencyMs
	}
	return 0
}

func (x *BatchPredictResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BatchPredictResponse) GetErrorCount() int32 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

type HealthCheckResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Status            string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	UptimeSeconds     int64                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	LoadedModelsCount int32                  `protobuf:"varint,3,opt,name=loaded_models_count,json=loadedModelsCount,proto3" json:"loaded_models_count,omitempty"`
	LoadedModels      []string               `protobuf:"bytes,4,rep,name=loaded_models,json=loadedModels,proto3" json:"loaded_models,omitempty"`
	SystemMetrics     map[string]string      `protobuf:"bytes,5,rep,name=system_metrics,json=systemMetrics,proto3" json:"system_metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_web_apps_python_ml_service_proto_ml_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_apps_python_ml_service_proto_ml_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_web_apps_python_ml_service_proto_ml_service_proto_rawDescGZIP(), []int{9}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthCheckResponse) GetLoadedModelsCount() int32 {
	if x != nil {
		return x.LoadedModelsCount
	}
	return 0
}

func (x *HealthCheckResponse) GetLoadedModels() []string {
	if x != nil {
		return x.LoadedModels
	}
	return nil
}

func (x *HealthCheckResponse) GetSystemMetrics() map[string]string {
	if x != nil {
		return x.SystemMetrics
	}
	return nil
}

type ModelInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ModelType     string                 `protobuf:"bytes,2,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	InputFeatures []string               `protobuf:"bytes,4,rep,name=input_features,json=inputFeatures,proto3" json:"input_features,omitempty"`
	OutputClasses []string               `protobuf:"bytes,5,rep,name=output_classes,json=outputClasses,proto3" json:"output_classes,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Loaded        bool                   `protobuf:"varint,7,opt,name=loaded,proto3" json:"loaded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfoResponse) Reset() {
	*x = ModelInfoResponse{}
	mi := &file_web_apps_python_ml_service_proto_ml_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfoResponse) ProtoMessage() {}

func (x *ModelInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_apps_python_ml_service_proto_ml_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfoResponse.ProtoReflect.Descriptor instead.
func (*ModelInfoResponse) Descriptor() ([]byte, []int) {
	return file_web_apps_python_ml_service_proto_ml_service_proto_rawDescGZIP(), []int{10}
}

func (x *ModelInfoResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ModelInfoResponse) GetModelType() string {
	if x != nil {
		return x.ModelType
	}
	return ""
}

func (x *ModelInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModelInfoResponse) GetInputFeatures() []string {
	if x != nil {
		return x.InputFeatures
	}
	return nil
}

func (x *ModelInfoResponse) GetOutputClasses() []string {
	if x != nil {
		return x.OutputClasses
	}
	return nil
}

func (x *ModelInfoResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ModelInfoResponse) GetLoaded() bool {
	if x != nil {
		return x.Loaded
	}
	return false
}

type LoadModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	LoadTimeMs    int64                  `protobuf:"varint,3,opt,name=load_time_ms,json=loadTimeMs,proto3" json:"load_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadModelResponse) Reset() {
	*x = LoadModelResponse{}
	mi := &file_web_apps_python_ml_service_proto_ml_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModelResponse) ProtoMessage() {}

func (x *LoadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_apps_python_ml_service_proto_ml_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModelResponse.ProtoReflect.Descriptor instead.
func (*LoadModelResponse) Descriptor() ([]byte, []int) {
	return file_web_apps_python_ml_service_proto_ml_service_proto_rawDescGZIP(), []int{11}
}

func (x *LoadModelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoadModelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoadModelResponse) GetLoadTimeMs() int64 {
	if x != nil {
		return x.LoadTimeMs
	}
	return 0
}

type UnloadModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadModelResponse) Reset() {
	*x = UnloadModelResponse{}
	mi := &file_web_apps_python_ml_service_proto_ml_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadModelResponse) ProtoMessage() {}

func (x *UnloadModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_apps_python_ml_service_proto_ml_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadModelResponse.ProtoReflect.Descriptor instead.
func (*UnloadModelResponse) Descriptor() ([]byte, []int) {
	return file_web_apps_python_ml_service_proto_ml_service_proto_rawDescGZIP(), []int{12}
}

func (x *UnloadModelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnloadModelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_web_apps_python_ml_service_proto_ml_service_proto protoreflect.FileDescriptor

const file_web_apps_python_ml_service_proto_ml_service_proto_rawDesc = "" +
	"\n" +
	"1web/apps/python-ml-service/proto/ml_service.proto\x12\x02ml\"\xe1\x01\n" +
	"\x0ePredictRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x1a\n" +
	"\bfeatures\x18\x02 \x03(\x01R\bfeatures\x12<\n" +
	"\bmetadata\x18\x03 \x03(\v2 .ml.PredictRequest.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x05R\ttimeoutMs\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x02\n" +
	"\x13BatchPredictRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x121\n" +
	"\ffeature_sets\x18\x02 \x03(\v2\x0e.ml.FeatureSetR\vfeatureSets\x12A\n" +
	"\bmetadata\x18\x03 \x03(\v2%.ml.BatchPredictRequest.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x05R\ttimeoutMs\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\n" +
	"FeatureSet\x12\x1a\n" +
	"\bfeatures\x18\x01 \x03(\x01R\bfeatures\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\"0\n" +
	"\x12HealthCheckRequest\x12\x1a\n" +
	"\bdetailed\x18\x01 \x01(\bR\bdetailed\"-\n" +
	"\x10ModelInfoRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\"\xc1\x01\n" +
	"\x10LoadModelRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x1d\n" +
	"\n" +
	"model_path\x18\x02 \x01(\tR\tmodelPath\x128\n" +
	"\x06config\x18\x03 \x03(\v2 .ml.LoadModelRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\x12UnloadModelRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\"\xb1\x02\n" +
	"\x0fPredictResponse\x12\x1e\n" +
	"\n" +
	"prediction\x18\x01 \x01(\x01R\n" +
	"prediction\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x03R\tlatencyMs\x12L\n" +
	"\rprobabilities\x18\x05 \x03(\v2&.ml.PredictResponse.ProbabilitiesEntryR\rprobabilities\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x1a@\n" +
	"\x12ProbabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xbd\x01\n" +
	"\x14BatchPredictResponse\x125\n" +
	"\vpredictions\x18\x01 \x03(\v2\x13.ml.PredictResponseR\vpredictions\x12(\n" +
	"\x10total_latency_ms\x18\x02 \x01(\x03R\x0etotalLatencyMs\x12#\n" +
	"\rsuccess_count\x18\x03 \x01(\x05R\fsuccessCount\x12\x1f\n" +
	"\verror_count\x18\x04 \x01(\x05R\n" +
	"errorCount\"\xbe\x02\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\x12.\n" +
	"\x13loaded_models_count\x18\x03 \x01(\x05R\x11loadedModelsCount\x12#\n" +
	"\rloaded_models\x18\x04 \x03(\tR\floadedModels\x12Q\n" +
	"\x0esystem_metrics\x18\x05 \x03(\v2*.ml.HealthCheckResponse.SystemMetricsEntryR\rsystemMetrics\x1a@\n" +
	"\x12SystemMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcb\x02\n" +
	"\x11ModelInfoResponse\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x1d\n" +
	"\n" +
	"model_type\x18\x02 \x01(\tR\tmodelType\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12%\n" +
	"\x0einput_features\x18\x04 \x03(\tR\rinputFeatures\x12%\n" +
	"\x0eoutput_classes\x18\x05 \x03(\tR\routputClasses\x12?\n" +
	"\bmetadata\x18\x06 \x03(\v2#.ml.ModelInfoResponse.MetadataEntryR\bmetadata\x12\x16\n" +
	"\x06loaded\x18\a \x01(\bR\x06loaded\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"i\n" +
	"\x11LoadModelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\fload_time_ms\x18\x03 \x01(\x03R\n" +
	"loadTimeMs\"I\n" +
	"\x13UnloadModelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xf9\x02\n" +
	"\tMLService\x122\n" +
	"\aPredict\x12\x12.ml.PredictRequest\x1a\x13.ml.PredictResponse\x12A\n" +
	"\fBatchPredict\x12\x17.ml.BatchPredictRequest\x1a\x18.ml.BatchPredictResponse\x12>\n" +
	"\vHealthCheck\x12\x16.ml.HealthCheckRequest\x1a\x17.ml.HealthCheckResponse\x12;\n" +
	"\fGetModelInfo\x12\x14.ml.ModelInfoRequest\x1a\x15.ml.ModelInfoResponse\x128\n" +
	"\tLoadModel\x12\x14.ml.LoadModelRequest\x1a\x15.ml.LoadModelResponse\x12>\n" +
	"\vUnloadModel\x12\x16.ml.UnloadModelRequest\x1a\x17.ml.UnloadModelResponseB1Z/github.com/schlep-engine/schlep-engine/proto/mlb\x06proto3"

var (
	file_web_apps_python_ml_service_proto_ml_service_proto_rawDescOnce sync.Once
	file_web_apps_python_ml_service_proto_ml_service_proto_rawDescData []byte
)

func file_web_apps_python_ml_service_proto_ml_service_proto_rawDescGZIP() []byte {
	file_web_apps_python_ml_service_proto_ml_service_proto_rawDescOnce.Do(func() {
		file_web_apps_python_ml_service_proto_ml_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_web_apps_python_ml_service_proto_ml_service_proto_rawDesc), len(file_web_apps_python_ml_service_proto_ml_service_proto_rawDesc)))
	})
	return file_web_apps_python_ml_service_proto_ml_service_proto_rawDescData
}

var file_web_apps_python_ml_service_proto_ml_service_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_web_apps_python_ml_service_proto_ml_service_proto_goTypes = []any{
	(*PredictRequest)(nil),       // 0: ml.PredictRequest
	(*BatchPredictRequest)(nil),  // 1: ml.BatchPredictRequest
	(*FeatureSet)(nil),           // 2: ml.FeatureSet
	(*HealthCheckRequest)(nil),   // 3: ml.HealthCheckRequest
	(*ModelInfoRequest)(nil),     // 4: ml.ModelInfoRequest
	(*LoadModelRequest)(nil),     // 5: ml.LoadModelRequest
	(*UnloadModelRequest)(nil),   // 6: ml.UnloadModelRequest
	(*PredictResponse)(nil),      // 7: ml.PredictResponse
	(*BatchPredictResponse)(nil), // 8: ml.BatchPredictResponse
	(*HealthCheckResponse)(nil),  // 9: ml.HealthCheckResponse
	(*ModelInfoResponse)(nil),    // 10: ml.ModelInfoResponse
	(*LoadModelResponse)(nil),    // 11: ml.LoadModelResponse
	(*UnloadModelResponse)(nil),  // 12: ml.UnloadModelResponse
	nil,                          // 13: ml.PredictRequest.MetadataEntry
	nil,                          // 14: ml.BatchPredictRequest.MetadataEntry
	nil,                          // 15: ml.LoadModelRequest.ConfigEntry
	nil,                          // 16: ml.PredictResponse.ProbabilitiesEntry
	nil,                          // 17: ml.HealthCheckResponse.SystemMetricsEntry
	nil,                          // 18: ml.ModelInfoResponse.MetadataEntry
}
var file_web_apps_python_ml_service_proto_ml_service_proto_depIdxs = []int32{
	13, // 0: ml.PredictRequest.metadata:type_name -> ml.PredictRequest.MetadataEntry
	2,  // 1: ml.BatchPredictRequest.feature_sets:type_name -> ml.FeatureSet
	14, // 2: ml.BatchPredictRequest.metadata:type_name -> ml.BatchPredictRequest.MetadataEntry
	15, // 3: ml.LoadModelRequest.config:type_name -> ml.LoadModelRequest.ConfigEntry
	16, // 4: ml.PredictResponse.probabilities:type_name -> ml.PredictResponse.ProbabilitiesEntry
	7,  // 5: ml.BatchPredictResponse.predictions:type_name -> ml.PredictResponse
	17, // 6: ml.HealthCheckResponse.system_metrics:type_name -> ml.HealthCheckResponse.SystemMetricsEntry
	18, // 7: ml.ModelInfoResponse.metadata:type_name -> ml.ModelInfoResponse.MetadataEntry
	0,  // 8: ml.MLService.Predict:input_type -> ml.PredictRequest
	1,  // 9: ml.MLService.BatchPredict:input_type -> ml.BatchPredictRequest
	3,  // 10: ml.MLService.HealthCheck:input_type -> ml.HealthCheckRequest
	4,  // 11: ml.MLService.GetModelInfo:input_type -> ml.ModelInfoRequest
	5,  // 12: ml.MLService.LoadModel:input_type -> ml.LoadModelRequest
	6,  // 13: ml.MLService.UnloadModel:input_type -> ml.UnloadModelRequest
	7,  // 14: ml.MLService.Predict:output_type -> ml.PredictResponse
	8,  // 15: ml.MLService.BatchPredict:output_type -> ml.BatchPredictResponse
	9,  // 16: ml.MLService.HealthCheck:output_type -> ml.HealthCheckResponse
	10, // 17: ml.MLService.GetModelInfo:output_type -> ml.ModelInfoResponse
	11, // 18: ml.MLService.LoadModel:output_type -> ml.LoadModelResponse
	12, // 19: ml.MLService.UnloadModel:output_type -> ml.UnloadModelResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_web_apps_python_ml_service_proto_ml_service_proto_init() }
func file_web_apps_python_ml_service_proto_ml_service_proto_init() {
	if File_web_apps_python_ml_service_proto_ml_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_web_apps_python_ml_service_proto_ml_service_proto_rawDesc), len(file_web_apps_python_ml_service_proto_ml_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_web_apps_python_ml_service_proto_ml_service_proto_goTypes,
		DependencyIndexes: file_web_apps_python_ml_service_proto_ml_service_proto_depIdxs,
		MessageInfos:      file_web_apps_python_ml_service_proto_ml_service_proto_msgTypes,
	}.Build()
	File_web_apps_python_ml_service_proto_ml_service_proto = out.File
	file_web_apps_python_ml_service_proto_ml_service_proto_goTypes = nil
	file_web_apps_python_ml_service_proto_ml_service_proto_depIdxs = nil
}
