#!/bin/bash

# Staging Environment Setup Script for Schlep-engine
# This script sets up a complete staging environment that mirrors production

set -e

echo "🚀 Setting up Staging Environment for Schlep-engine..."

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Function to check if port is available
port_available() {
    ! nc -z localhost $1 2>/dev/null
}

# Function to create directory if it doesn't exist
create_directory() {
    if [ ! -d "$1" ]; then
        mkdir -p "$1"
        print_success "Created directory: $1"
    else
        print_status "Directory already exists: $1"
    fi
}

# Function to check prerequisites
check_prerequisites() {
    print_status "Checking prerequisites..."
    
    local missing_deps=()
    
    if ! command_exists docker; then
        missing_deps+=("docker")
    fi
    
    if ! command_exists docker-compose; then
        missing_deps+=("docker-compose")
    fi
    
    if ! command_exists curl; then
        missing_deps+=("curl")
    fi
    
    if ! command_exists nc; then
        missing_deps+=("netcat")
    fi
    
    if [ ${#missing_deps[@]} -ne 0 ]; then
        print_error "Missing dependencies: ${missing_deps[*]}"
        print_status "Please install the missing dependencies and run this script again."
        exit 1
    fi
    
    # Check Docker is running
    if ! docker info >/dev/null 2>&1; then
        print_error "Docker is not running. Please start Docker and try again."
        exit 1
    fi
    
    print_success "All prerequisites are available"
}

# Function to create staging environment file
create_staging_env() {
    print_status "Creating staging environment configuration..."
    
    cat > .env.staging << EOF
# Staging Environment Configuration
# Generated by setup_staging.sh

# Environment
ENVIRONMENT=staging
APP_VERSION=1.0.0
DEBUG=false

# Database
STAGING_DB_HOST=staging-db
STAGING_DB_PORT=5432
STAGING_DB_NAME=igris_overture_staging
STAGING_DB_USER=schlep_staging
STAGING_DB_PASSWORD=staging_secure_password_$(openssl rand -hex 16)

# Redis
STAGING_REDIS_HOST=staging-redis
STAGING_REDIS_PORT=6379
STAGING_REDIS_PASSWORD=staging_redis_$(openssl rand -hex 16)

# Storage
STAGING_STORAGE_PROVIDER=gcs
STAGING_STORAGE_BUCKET=igris-inertial-staging
STAGING_STORAGE_CREDENTIALS_PATH=/app/credentials/staging-storage-key.json
STAGING_STORAGE_REGION=us-central1
STAGING_CDN_URL=https://staging-cdn.igris-inertial.com

# Security
STAGING_SECRET_KEY=staging_secret_$(openssl rand -hex 32)
ACCESS_TOKEN_EXPIRE_MINUTES=30
REFRESH_TOKEN_EXPIRE_DAYS=7
PASSWORD_MIN_LENGTH=8
MAX_LOGIN_ATTEMPTS=5
LOCKOUT_DURATION_MINUTES=15

# Monitoring
STAGING_SENTRY_DSN=https://your-sentry-dsn@sentry.io/staging
SENTRY_ENVIRONMENT=staging
LOG_LEVEL=INFO
LOG_FILE=/var/log/igris-inertial/app.log
PROMETHEUS_ENABLED=true
METRICS_RETENTION_DAYS=30

# Celery
STAGING_CELERY_BROKER_URL=redis://:staging_redis_$(openssl rand -hex 16)@staging-redis:6379/0
STAGING_CELERY_RESULT_BACKEND=redis://:staging_redis_$(openssl rand -hex 16)@staging-redis:6379/0

# External Services
STAGING_ML_SERVICE_URL=https://staging-ml.igris-inertial.com
STAGING_EMAIL_SERVICE_URL=https://staging-email.igris-inertial.com
STAGING_NOTIFICATION_SERVICE_URL=https://staging-notifications.igris-inertial.com

# CORS
STAGING_ALLOWED_ORIGINS=http://localhost:3001,https://staging.igris-inertial.com
STAGING_ALLOWED_HOSTS=staging.igris-inertial.com,localhost

# Rate Limiting
RATE_LIMIT_REQUESTS=100
RATE_LIMIT_WINDOW=60

# File Upload
MAX_FILE_SIZE=100000000
ALLOWED_FILE_TYPES=csv,json,xlsx,parquet

# Feature Flags
ENABLE_ADVANCED_AI=true
ENABLE_ML_PIPELINE=true
ENABLE_DATA_PROCESSING=true
ENABLE_STORAGE=true
ENABLE_MONITORING=true
ENABLE_SECURITY=true
EOF
    
    print_success "Staging environment configuration created: .env.staging"
}

# Function to create staging directories
create_staging_directories() {
    print_status "Creating staging directories..."
    
    create_directory "staging"
    create_directory "staging/logs"
    create_directory "staging/data"
    create_directory "staging/credentials"
    create_directory "staging/backups"
    create_directory "staging/monitoring"
    create_directory "staging/monitoring/prometheus"
    create_directory "staging/monitoring/grafana"
    create_directory "staging/monitoring/alertmanager"
    
    print_success "Staging directories created"
}

# Function to create staging database initialization script
create_staging_db_init() {
    print_status "Creating staging database initialization script..."
    
    cat > staging/init-staging-db.sql << EOF
-- Staging Database Initialization Script

-- Create staging database
CREATE DATABASE igris_overture_staging;

-- Create staging user
CREATE USER schlep_staging WITH PASSWORD 'staging_secure_password';

-- Grant privileges
GRANT ALL PRIVILEGES ON DATABASE igris_overture_staging TO schlep_staging;
GRANT CREATE ON DATABASE igris_overture_staging TO schlep_staging;

-- Connect to staging database
\c igris_overture_staging;

-- Grant schema privileges
GRANT ALL ON SCHEMA public TO schlep_staging;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO schlep_staging;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO schlep_staging;

-- Create staging-specific extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Create staging-specific tables (if needed)
CREATE TABLE IF NOT EXISTS staging_metadata (
    id SERIAL PRIMARY KEY,
    environment VARCHAR(50) NOT NULL DEFAULT 'staging',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert staging metadata
INSERT INTO staging_metadata (environment) VALUES ('staging') ON CONFLICT DO NOTHING;
EOF
    
    print_success "Staging database initialization script created"
}

# Function to create staging monitoring configuration
create_staging_monitoring() {
    print_status "Creating staging monitoring configuration..."
    
    # Create Prometheus configuration
    cat > staging/monitoring/prometheus/prometheus.yml << EOF
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: staging
    service: igris-inertial

scrape_configs:
  - job_name: 'igris-inertial-staging'
    static_configs:
      - targets: ['staging-backend:8000']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    scheme: http
    tls_config:
      insecure_skip_verify: true

  - job_name: 'staging-health'
    static_configs:
      - targets: ['staging-backend:8000']
    metrics_path: '/api/v1/health'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true
    scheme: http
    tls_config:
      insecure_skip_verify: true

  - job_name: 'staging-postgresql'
    static_configs:
      - targets: ['staging-db:5432']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    tls_config:
      insecure_skip_verify: true

  - job_name: 'staging-redis'
    static_configs:
      - targets: ['staging-redis:6379']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    tls_config:
      insecure_skip_verify: true
EOF
    
    # Create AlertManager configuration
    cat > staging/monitoring/alertmanager/alertmanager.yml << EOF
global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK_URL'

route:
  group_by: ['alertname', 'environment']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'staging-team'
  routes:
    - match:
        severity: critical
      receiver: 'staging-critical'
      repeat_interval: 30m

receivers:
  - name: 'staging-team'
    slack_configs:
      - channel: '#staging-alerts'
        title: 'Staging Alert: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        send_resolved: true

  - name: 'staging-critical'
    slack_configs:
      - channel: '#staging-critical'
        title: 'CRITICAL: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        send_resolved: true
EOF
    
    # Create Grafana datasource configuration
    cat > staging/monitoring/grafana/datasources.yml << EOF
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://staging-prometheus:9090
    isDefault: true
    editable: true
EOF
    
    print_success "Staging monitoring configuration created"
}

# Function to create staging deployment script
create_staging_deployment_script() {
    print_status "Creating staging deployment script..."
    
    cat > staging/deploy.sh << 'EOF'
#!/bin/bash

# Staging Deployment Script

set -e

echo "🚀 Deploying to Staging Environment..."

# Load environment variables
if [ -f .env.staging ]; then
    export $(cat .env.staging | grep -v '^#' | xargs)
fi

# Function to print colored output
print_status() {
    echo -e "\033[0;34m[INFO]\033[0m $1"
}

print_success() {
    echo -e "\033[0;32m[SUCCESS]\033[0m $1"
}

print_error() {
    echo -e "\033[0;31m[ERROR]\033[0m $1"
}

# Check if Docker is running
if ! docker info >/dev/null 2>&1; then
    print_error "Docker is not running"
    exit 1
fi

# Build and deploy
print_status "Building and deploying staging environment..."

# Stop existing containers
print_status "Stopping existing containers..."
docker-compose -f docker-compose.staging.yml down

# Remove old volumes (optional - uncomment if you want fresh data)
# print_status "Removing old volumes..."
# docker volume rm igris-inertial_staging_postgres_data igris-inertial_staging_redis_data 2>/dev/null || true

# Build images
print_status "Building Docker images..."
docker-compose -f docker-compose.staging.yml build

# Start services
print_status "Starting services..."
docker-compose -f docker-compose.staging.yml up -d

# Wait for services to be ready
print_status "Waiting for services to be ready..."
sleep 30

# Run database migrations
print_status "Running database migrations..."
docker-compose -f docker-compose.staging.yml exec -T staging-backend alembic upgrade head

# Health check
print_status "Performing health check..."
for i in {1..10}; do
    if curl -f http://localhost:8001/api/v1/health/simple >/dev/null 2>&1; then
        print_success "Health check passed"
        break
    else
        print_status "Health check attempt $i/10 failed, retrying..."
        sleep 10
    fi
done

# Final health check
if curl -f http://localhost:8001/api/v1/health/simple >/dev/null 2>&1; then
    print_success "Staging deployment completed successfully!"
    echo ""
    echo "🌐 Staging Environment URLs:"
    echo "  - Backend API: http://localhost:8001"
    echo "  - API Documentation: http://localhost:8001/docs"
    echo "  - Health Check: http://localhost:8001/api/v1/health"
    echo "  - Metrics: http://localhost:8001/api/v1/metrics"
    echo "  - Prometheus: http://localhost:9091"
    echo "  - Grafana: http://localhost:3001 (admin/admin)"
    echo "  - AlertManager: http://localhost:9094"
    echo "  - Flower (Celery): http://localhost:5556"
    echo ""
else
    print_error "Health check failed after deployment"
    exit 1
fi
EOF
    
    chmod +x staging/deploy.sh
    print_success "Staging deployment script created: staging/deploy.sh"
}

# Function to create staging backup script
create_staging_backup_script() {
    print_status "Creating staging backup script..."
    
    cat > staging/backup.sh << 'EOF'
#!/bin/bash

# Staging Backup Script

set -e

BACKUP_DIR="staging/backups"
DATE=$(date +%Y%m%d_%H%M%S)
BACKUP_NAME="staging_backup_$DATE"

echo "💾 Creating staging backup: $BACKUP_NAME"

# Create backup directory
mkdir -p "$BACKUP_DIR"

# Backup database
echo "Backing up database..."
docker-compose -f docker-compose.staging.yml exec -T staging-db pg_dump -U schlep_staging igris_overture_staging > "$BACKUP_DIR/${BACKUP_NAME}_database.sql"

# Backup Redis data (if needed)
echo "Backing up Redis data..."
docker-compose -f docker-compose.staging.yml exec -T staging-redis redis-cli --rdb /data/dump.rdb
docker cp $(docker-compose -f docker-compose.staging.yml ps -q staging-redis):/data/dump.rdb "$BACKUP_DIR/${BACKUP_NAME}_redis.rdb"

# Backup logs
echo "Backing up logs..."
docker-compose -f docker-compose.staging.yml exec -T staging-backend tar -czf /tmp/logs.tar.gz /var/log/igris-inertial/
docker cp $(docker-compose -f docker-compose.staging.yml ps -q staging-backend):/tmp/logs.tar.gz "$BACKUP_DIR/${BACKUP_NAME}_logs.tar.gz"

# Create backup archive
echo "Creating backup archive..."
cd "$BACKUP_DIR"
tar -czf "${BACKUP_NAME}.tar.gz" "${BACKUP_NAME}_database.sql" "${BACKUP_NAME}_redis.rdb" "${BACKUP_NAME}_logs.tar.gz"
rm "${BACKUP_NAME}_database.sql" "${BACKUP_NAME}_redis.rdb" "${BACKUP_NAME}_logs.tar.gz"

echo "✅ Backup completed: $BACKUP_DIR/${BACKUP_NAME}.tar.gz"
EOF
    
    chmod +x staging/backup.sh
    print_success "Staging backup script created: staging/backup.sh"
}

# Function to create staging restore script
create_staging_restore_script() {
    print_status "Creating staging restore script..."
    
    cat > staging/restore.sh << 'EOF'
#!/bin/bash

# Staging Restore Script

set -e

if [ $# -eq 0 ]; then
    echo "Usage: $0 <backup_file>"
    echo "Example: $0 staging/backups/staging_backup_20240115_143022.tar.gz"
    exit 1
fi

BACKUP_FILE="$1"
BACKUP_DIR="staging/backups"
RESTORE_DIR="$BACKUP_DIR/restore_$(date +%Y%m%d_%H%M%S)"

echo "🔄 Restoring staging environment from: $BACKUP_FILE"

# Check if backup file exists
if [ ! -f "$BACKUP_FILE" ]; then
    echo "Error: Backup file not found: $BACKUP_FILE"
    exit 1
fi

# Create restore directory
mkdir -p "$RESTORE_DIR"
cd "$RESTORE_DIR"

# Extract backup
echo "Extracting backup..."
tar -xzf "../../$BACKUP_FILE"

# Stop services
echo "Stopping services..."
docker-compose -f ../../docker-compose.staging.yml down

# Restore database
echo "Restoring database..."
docker-compose -f ../../docker-compose.staging.yml up -d staging-db
sleep 10
docker-compose -f ../../docker-compose.staging.yml exec -T staging-db psql -U schlep_staging -d postgres -c "DROP DATABASE IF EXISTS igris_overture_staging;"
docker-compose -f ../../docker-compose.staging.yml exec -T staging-db psql -U schlep_staging -d postgres -c "CREATE DATABASE igris_overture_staging;"
docker-compose -f ../../docker-compose.staging.yml exec -T staging-db psql -U schlep_staging -d igris_overture_staging < *_database.sql

# Restore Redis (if needed)
echo "Restoring Redis data..."
docker-compose -f ../../docker-compose.staging.yml up -d staging-redis
sleep 5
docker cp *_redis.rdb $(docker-compose -f ../../docker-compose.staging.yml ps -q staging-redis):/data/dump.rdb
docker-compose -f ../../docker-compose.staging.yml exec -T staging-redis redis-cli BGREWRITEAOF

# Start all services
echo "Starting all services..."
docker-compose -f ../../docker-compose.staging.yml up -d

# Wait for services to be ready
echo "Waiting for services to be ready..."
sleep 30

# Health check
echo "Performing health check..."
if curl -f http://localhost:8001/api/v1/health/simple >/dev/null 2>&1; then
    echo "✅ Restore completed successfully!"
else
    echo "❌ Health check failed after restore"
    exit 1
fi

# Cleanup
cd ../..
rm -rf "$RESTORE_DIR"

echo "🔄 Restore completed successfully!"
EOF
    
    chmod +x staging/restore.sh
    print_success "Staging restore script created: staging/restore.sh"
}

# Function to create staging monitoring script
create_staging_monitoring_script() {
    print_status "Creating staging monitoring script..."
    
    cat > staging/monitor.sh << 'EOF'
#!/bin/bash

# Staging Monitoring Script

set -e

echo "📊 Staging Environment Monitoring Report"
echo "========================================"
echo ""

# Function to check service status
check_service() {
    local service_name="$1"
    local port="$2"
    local endpoint="$3"
    
    if nc -z localhost "$port" 2>/dev/null; then
        if [ -n "$endpoint" ]; then
            if curl -f "http://localhost:$port$endpoint" >/dev/null 2>&1; then
                echo "✅ $service_name is running and healthy"
                return 0
            else
                echo "⚠️  $service_name is running but health check failed"
                return 1
            fi
        else
            echo "✅ $service_name is running"
            return 0
        fi
    else
        echo "❌ $service_name is not running"
        return 1
    fi
}

# Check all services
echo "Service Status:"
check_service "Backend API" 8001 "/api/v1/health/simple"
check_service "Database" 5433
check_service "Redis" 6380
check_service "Prometheus" 9091
check_service "Grafana" 3001
check_service "AlertManager" 9094
check_service "Flower (Celery)" 5556

echo ""
echo "Resource Usage:"
echo "==============="

# Get container resource usage
if command -v docker >/dev/null 2>&1; then
    echo "Container Resource Usage:"
    docker stats --no-stream --format "table {{.Container}}\t{{.CPUPerc}}\t{{.MemUsage}}\t{{.NetIO}}"
fi

echo ""
echo "Recent Logs:"
echo "============"

# Show recent logs from backend
if docker-compose -f docker-compose.staging.yml ps staging-backend | grep -q "Up"; then
    echo "Backend Logs (last 10 lines):"
    docker-compose -f docker-compose.staging.yml logs --tail=10 staging-backend
else
    echo "Backend container is not running"
fi

echo ""
echo "Database Status:"
echo "================"

# Check database connections
if nc -z localhost 5433 2>/dev/null; then
    echo "Database is accessible"
    # You can add more database checks here
else
    echo "Database is not accessible"
fi

echo ""
echo "Monitoring URLs:"
echo "================"
echo "  - Backend API: http://localhost:8001"
echo "  - API Documentation: http://localhost:8001/docs"
echo "  - Health Check: http://localhost:8001/api/v1/health"
echo "  - Metrics: http://localhost:8001/api/v1/metrics"
echo "  - Prometheus: http://localhost:9091"
echo "  - Grafana: http://localhost:3001 (admin/admin)"
echo "  - AlertManager: http://localhost:9094"
echo "  - Flower (Celery): http://localhost:5556"
EOF
    
    chmod +x staging/monitor.sh
    print_success "Staging monitoring script created: staging/monitor.sh"
}

# Function to create staging cleanup script
create_staging_cleanup_script() {
    print_status "Creating staging cleanup script..."
    
    cat > staging/cleanup.sh << 'EOF'
#!/bin/bash

# Staging Cleanup Script

set -e

echo "🧹 Cleaning up staging environment..."

# Function to print colored output
print_status() {
    echo -e "\033[0;34m[INFO]\033[0m $1"
}

print_success() {
    echo -e "\033[0;32m[SUCCESS]\033[0m $1"
}

print_warning() {
    echo -e "\033[1;33m[WARNING]\033[0m $1"
}

# Stop all services
print_status "Stopping all services..."
docker-compose -f docker-compose.staging.yml down

# Remove containers
print_status "Removing containers..."
docker-compose -f docker-compose.staging.yml rm -f

# Remove volumes (optional - uncomment if you want to remove all data)
read -p "Do you want to remove all staging data (volumes)? This will delete all data! (y/N): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    print_warning "Removing all staging data..."
    docker volume rm igris-inertial_staging_postgres_data 2>/dev/null || true
    docker volume rm igris-inertial_staging_redis_data 2>/dev/null || true
    docker volume rm igris-inertial_staging_logs 2>/dev/null || true
    docker volume rm igris-inertial_staging_uploads 2>/dev/null || true
    docker volume rm igris-inertial_staging_prometheus_data 2>/dev/null || true
    docker volume rm igris-inertial_staging_grafana_data 2>/dev/null || true
    docker volume rm igris-inertial_staging_alertmanager_data 2>/dev/null || true
    print_success "All staging data removed"
else
    print_status "Keeping staging data"
fi

# Remove networks
print_status "Removing networks..."
docker network rm igris-inertial_schlep-staging-network 2>/dev/null || true

# Clean up old images (optional)
read -p "Do you want to remove unused Docker images? (y/N): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    print_status "Removing unused images..."
    docker image prune -f
    print_success "Unused images removed"
fi

print_success "Staging environment cleanup completed!"
EOF
    
    chmod +x staging/cleanup.sh
    print_success "Staging cleanup script created: staging/cleanup.sh"
}

# Function to create staging documentation
create_staging_documentation() {
    print_status "Creating staging documentation..."
    
    cat > staging/README.md << 'EOF'
# Staging Environment Documentation

## Overview

This directory contains the staging environment setup for Schlep-engine. The staging environment mirrors production for pre-deployment testing.

## Quick Start

1. **Setup Environment:**
   ```bash
   ./scripts/setup_staging.sh
   ```

2. **Deploy to Staging:**
   ```bash
   cd staging
   ./deploy.sh
   ```

3. **Monitor Staging:**
   ```bash
   ./monitor.sh
   ```

## Environment Configuration

The staging environment uses the following configuration:

- **Database:** PostgreSQL 15 with staging-specific database
- **Cache:** Redis with staging-specific instance
- **Storage:** Google Cloud Storage (staging bucket)
- **Monitoring:** Prometheus, Grafana, AlertManager
- **Background Processing:** Celery with Redis broker

## Services

| Service | Port | Description |
|---------|------|-------------|
| Backend API | 8001 | Main application API |
| Database | 5433 | PostgreSQL database |
| Redis | 6380 | Redis cache |
| Prometheus | 9091 | Metrics collection |
| Grafana | 3001 | Monitoring dashboards |
| AlertManager | 9094 | Alert management |
| Flower | 5556 | Celery monitoring |

## URLs

- **Backend API:** http://localhost:8001
- **API Documentation:** http://localhost:8001/docs
- **Health Check:** http://localhost:8001/api/v1/health
- **Metrics:** http://localhost:8001/api/v1/metrics
- **Prometheus:** http://localhost:9091
- **Grafana:** http://localhost:3001 (admin/admin)
- **AlertManager:** http://localhost:9094
- **Flower (Celery):** http://localhost:5556

## Scripts

- `deploy.sh` - Deploy staging environment
- `backup.sh` - Create backup of staging data
- `restore.sh` - Restore staging from backup
- `monitor.sh` - Monitor staging environment
- `cleanup.sh` - Clean up staging environment

## Environment Variables

The staging environment uses `.env.staging` for configuration. Key variables:

- `STAGING_DB_PASSWORD` - Database password
- `STAGING_REDIS_PASSWORD` - Redis password
- `STAGING_SECRET_KEY` - Application secret key
- `STAGING_SENTRY_DSN` - Sentry DSN for error tracking
- `STAGING_STORAGE_BUCKET` - Storage bucket name

## Monitoring

The staging environment includes comprehensive monitoring:

- **Health Checks:** Automatic health monitoring
- **Metrics:** Prometheus metrics collection
- **Logs:** Structured logging with rotation
- **Alerts:** AlertManager for notifications
- **Dashboards:** Grafana dashboards

## Backup and Restore

### Create Backup
```bash
./backup.sh
```

### Restore from Backup
```bash
./restore.sh staging/backups/staging_backup_YYYYMMDD_HHMMSS.tar.gz
```

## Troubleshooting

### Common Issues

1. **Port Conflicts:** Ensure ports 8001, 5433, 6380, 9091, 3001, 9094, 5556 are available
2. **Database Connection:** Check database credentials in `.env.staging`
3. **Redis Connection:** Verify Redis password configuration
4. **Storage Access:** Ensure storage credentials are properly configured

### Logs

View logs for specific services:
```bash
# Backend logs
docker-compose -f docker-compose.staging.yml logs staging-backend

# Database logs
docker-compose -f docker-compose.staging.yml logs staging-db

# Redis logs
docker-compose -f docker-compose.staging.yml logs staging-redis
```

### Health Checks

Check service health:
```bash
# Overall health
curl http://localhost:8001/api/v1/health

# Simple health check
curl http://localhost:8001/api/v1/health/simple

# Database health
curl http://localhost:8001/api/v1/health/database

# Redis health
curl http://localhost:8001/api/v1/health/redis
```

## Security

The staging environment includes security features:

- **Rate Limiting:** API rate limiting
- **Authentication:** JWT-based authentication
- **Authorization:** Role-based access control
- **Audit Logging:** Comprehensive audit trails
- **Data Encryption:** Field-level encryption

## Performance

The staging environment is configured for performance testing:

- **Connection Pooling:** Database connection pooling
- **Caching:** Redis caching layer
- **Background Processing:** Celery for async tasks
- **Monitoring:** Performance metrics collection

## Maintenance

Regular maintenance tasks:

1. **Database Maintenance:** Regular backups and cleanup
2. **Log Rotation:** Automatic log rotation
3. **Security Updates:** Regular security patches
4. **Performance Monitoring:** Monitor and optimize performance

## Support

For issues with the staging environment:

1. Check the logs: `./monitor.sh`
2. Review the documentation
3. Contact the development team
EOF
    
    print_success "Staging documentation created: staging/README.md"
}

# Function to test staging setup
test_staging_setup() {
    print_status "Testing staging setup..."
    
    # Check if Docker Compose file exists
    if [ ! -f "docker-compose.staging.yml" ]; then
        print_error "Docker Compose staging file not found"
        return 1
    fi
    
    # Check if environment file exists
    if [ ! -f ".env.staging" ]; then
        print_error "Staging environment file not found"
        return 1
    fi
    
    # Validate Docker Compose file
    if docker-compose -f docker-compose.staging.yml config >/dev/null 2>&1; then
        print_success "Docker Compose staging configuration is valid"
    else
        print_error "Docker Compose staging configuration is invalid"
        return 1
    fi
    
    print_success "Staging setup test completed"
}

# Function to display setup summary
display_staging_summary() {
    echo ""
    echo "🎉 Staging Environment Setup Complete!"
    echo ""
    echo "📋 Setup Summary:"
    echo "  ✅ Prerequisites checked"
    echo "  ✅ Staging environment configuration created"
    echo "  ✅ Staging directories created"
    echo "  ✅ Database initialization script created"
    echo "  ✅ Monitoring configuration created"
    echo "  ✅ Deployment script created"
    echo "  ✅ Backup and restore scripts created"
    echo "  ✅ Monitoring script created"
    echo "  ✅ Cleanup script created"
    echo "  ✅ Documentation created"
    echo "  ✅ Setup test completed"
    echo ""
    echo "🚀 Next Steps:"
    echo "  1. Review and customize .env.staging configuration"
    echo "  2. Deploy staging environment: cd staging && ./deploy.sh"
    echo "  3. Monitor staging: ./monitor.sh"
    echo "  4. Access staging services:"
    echo "     - Backend API: http://localhost:8001"
    echo "     - Grafana: http://localhost:3001 (admin/admin)"
    echo "     - Prometheus: http://localhost:9091"
    echo ""
    echo "📚 Documentation:"
    echo "  - Staging README: staging/README.md"
    echo "  - Deployment: staging/deploy.sh"
    echo "  - Monitoring: staging/monitor.sh"
    echo "  - Backup: staging/backup.sh"
    echo "  - Restore: staging/restore.sh"
    echo "  - Cleanup: staging/cleanup.sh"
    echo ""
    echo "🔧 Configuration Files:"
    echo "  - Environment: .env.staging"
    echo "  - Docker Compose: docker-compose.staging.yml"
    echo "  - Nginx: nginx/nginx.staging.conf"
    echo "  - Prometheus: prometheus.staging.yml"
    echo "  - AlertManager: alertmanager.staging.yml"
    echo ""
}

# Main setup function
main() {
    echo "🚀 Starting Staging Environment Setup..."
    echo ""
    
    # Check prerequisites
    check_prerequisites
    
    # Create staging environment file
    create_staging_env
    
    # Create staging directories
    create_staging_directories
    
    # Create staging database initialization script
    create_staging_db_init
    
    # Create staging monitoring configuration
    create_staging_monitoring
    
    # Create staging deployment script
    create_staging_deployment_script
    
    # Create staging backup script
    create_staging_backup_script
    
    # Create staging restore script
    create_staging_restore_script
    
    # Create staging monitoring script
    create_staging_monitoring_script
    
    # Create staging cleanup script
    create_staging_cleanup_script
    
    # Create staging documentation
    create_staging_documentation
    
    # Test staging setup
    test_staging_setup
    
    # Display summary
    display_staging_summary
}

# Run main function
main "$@" 