apiVersion: v1
kind: Namespace
metadata:
  name: schlep-engine
  labels:
    name: schlep-engine
    env: production
    managed-by: kubernetes
    app.kubernetes.io/name: schlep-engine
    app.kubernetes.io/version: v1.0.0
---
apiVersion: v1
kind: Namespace
metadata:
  name: schlep-engine-staging
  labels:
    name: schlep-engine-staging
    env: staging
    managed-by: kubernetes
    app.kubernetes.io/name: schlep-engine
    app.kubernetes.io/version: v1.0.0
---
apiVersion: v1
kind: Namespace
metadata:
  name: schlep-engine-monitoring
  labels:
    name: schlep-engine-monitoring
    env: production
    managed-by: kubernetes
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/version: v1.0.0