const path = require('path');

const docsAppRoot = path.resolve(__dirname, '..');
const repoRoot = path.resolve(docsAppRoot, '../../..');
const docsDir = path.join(docsAppRoot, 'docs');
const generatedDir = path.join(docsAppRoot, 'lib', 'generated');

const sdkSupport = {
  generated_by: 'scripts/generate-docs-artifacts.js',
  native_sdk_note:
    'First-class native SDKs are JavaScript/TypeScript, Go, and Rust. Python remains preview. Java, C#, and Ruby should use the OpenAI-compatible API until native SDKs are production-ready.',
  rows: [
    {
      language: 'JavaScript / TypeScript',
      status: 'production-ready',
      package: '@igris-inertial/sdk',
      install: 'npm install @igris-inertial/sdk',
      import: "import { IgrisClient } from '@igris-inertial/sdk';",
      notes: 'Preferred native SDK for browser and Node.js integrations.',
    },
    {
      language: 'Go',
      status: 'production-ready',
      package: 'github.com/igris-inertial/go-sdk',
      install: 'go get github.com/igris-inertial/go-sdk',
      import: 'import igris "github.com/igris-inertial/go-sdk"',
      notes: 'Preferred native SDK for backend services and CLI tooling.',
    },
    {
      language: 'Rust',
      status: 'production-ready',
      package: 'igris-inertial',
      install: 'cargo add igris-inertial',
      import: 'use igris_inertial::IgrisClient;',
      notes: 'Preferred native SDK for systems and embedded integrations.',
    },
    {
      language: 'Python',
      status: 'preview',
      package: 'igris-inertial',
      install: 'pip install igris-inertial',
      import: 'from igris import IgrisClient',
      notes: 'Available in-repo, but not yet positioned as a first-class customer SDK.',
    },
    {
      language: 'Java',
      status: 'planned',
      package: 'n/a',
      install: 'Use an OpenAI-compatible client today',
      import: 'Use the OpenAI-compatible base URL',
      notes: 'Do not treat a native Java SDK as production-ready yet.',
    },
    {
      language: 'C#',
      status: 'planned',
      package: 'n/a',
      install: 'Use an OpenAI-compatible client today',
      import: 'Use the OpenAI-compatible base URL',
      notes: 'Do not treat a native C# SDK as production-ready yet.',
    },
    {
      language: 'Ruby',
      status: 'planned',
      package: 'n/a',
      install: 'Use an OpenAI-compatible client today',
      import: 'Use the OpenAI-compatible base URL',
      notes: 'Do not treat a native Ruby SDK as production-ready yet.',
    },
  ],
};

const apiSections = [
  {
    title: 'Inference & Integration',
    summary:
      'Supported cloud inference endpoints. `/v1/chat/completions` is OpenAI-compatible, while `/v1/infer` exposes the native Igris request contract.',
    endpoints: [
      {
        method: 'POST',
        path: '/v1/infer',
        auth: 'Deployment-dependent',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Native inference endpoint handled by Overture.',
      },
      {
        method: 'POST',
        path: '/v1/chat/completions',
        auth: 'Deployment-dependent',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'OpenAI-compatible chat completions endpoint.',
      },
      {
        method: 'GET',
        path: '/v1/health',
        auth: 'Public',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Health check for inference availability.',
      },
      {
        method: 'GET',
        path: '/v1/models',
        auth: 'Public',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Lists models visible to the inference layer.',
      },
      {
        method: 'GET',
        path: '/v1/providers/stats',
        auth: 'Public',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Provider latency, health, and routing statistics.',
      },
      {
        method: 'POST',
        path: '/v1/infer/multimodal',
        auth: 'Session or API key',
        surface: 'Cloud API',
        stability: 'preview',
        description: 'Multimodal inference endpoint.',
      },
      {
        method: 'GET',
        path: '/v1/infer/multimodal/stats',
        auth: 'Session or API key',
        surface: 'Cloud API',
        stability: 'preview',
        description: 'Multimodal request statistics.',
      },
    ],
  },
  {
    title: 'Runtime Distribution & Fleet Coordination',
    summary:
      'Supported endpoints for downloading `igris-runtime`, registering runtime instances, and managing fleet operations from the control plane.',
    endpoints: [
      {
        method: 'GET',
        path: '/v1/runtime/install',
        auth: 'Public',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Returns or redirects to the platform-specific runtime archive.',
      },
      {
        method: 'GET',
        path: '/v1/runtime/checksum',
        auth: 'Public',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Returns the SHA-256 checksum for a runtime archive.',
      },
      {
        method: 'GET',
        path: '/v1/runtime/download',
        auth: 'Session or API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Subscribed runtime binary download endpoint.',
      },
      {
        method: 'POST',
        path: '/api/v1/runtime/register',
        auth: 'igris_ API key',
        surface: 'Runtime coordination API',
        stability: 'stable',
        description: 'Registers a runtime instance against a tenant.',
      },
      {
        method: 'POST',
        path: '/api/v1/runtime/heartbeat',
        auth: 'igris_ API key',
        surface: 'Runtime coordination API',
        stability: 'stable',
        description: 'Heartbeat and liveness updates from runtime instances.',
      },
      {
        method: 'DELETE',
        path: '/api/v1/runtime/deregister',
        auth: 'igris_ API key',
        surface: 'Runtime coordination API',
        stability: 'stable',
        description: 'Removes a runtime instance from active fleet state.',
      },
      {
        method: 'GET',
        path: '/api/v1/runtime/list',
        auth: 'tenant_id query or authenticated tenant context',
        surface: 'Fleet management',
        stability: 'stable',
        description: 'Lists registered runtime instances for a tenant.',
      },
      {
        method: 'POST',
        path: '/api/v1/runtime/config/push',
        auth: 'Session cookie',
        surface: 'Fleet management',
        stability: 'stable',
        description: 'Queues configuration push commands for the fleet.',
      },
      {
        method: 'POST',
        path: '/api/v1/runtime/update',
        auth: 'Session cookie',
        surface: 'Fleet management',
        stability: 'stable',
        description: 'Queues OTA update commands for the fleet.',
      },
    ],
  },
  {
    title: 'Account, Trial, and Billing',
    summary:
      'Supported account and billing endpoints for subscription state and tenant API key lifecycle management.',
    endpoints: [
      {
        method: 'GET',
        path: '/api/subscription/status',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Returns subscription tier, status, and runtime usage.',
      },
      {
        method: 'GET',
        path: '/api/subscription/plans',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Lists available plans and checkout URLs.',
      },
      {
        method: 'GET',
        path: '/v1/account/api-key',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Returns current API key metadata without revealing the secret.',
      },
      {
        method: 'POST',
        path: '/v1/account/api-key',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Creates a new tenant API key and revokes the old one.',
      },
      {
        method: 'DELETE',
        path: '/v1/account/api-key',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Revokes the current tenant API key.',
      },
    ],
  },
  {
    title: 'Vault, Policy, and Governance',
    summary:
      'Supported BYOK and tenant policy routes.',
    endpoints: [
      {
        method: 'GET',
        path: '/v1/vault/keys',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Lists configured provider keys with masked values.',
      },
      {
        method: 'POST',
        path: '/v1/vault/keys',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Stores a provider key using `{ provider, key_name, api_key }`.',
      },
      {
        method: 'GET',
        path: '/v1/vault/keys/:provider',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Gets a single provider key record.',
      },
      {
        method: 'DELETE',
        path: '/v1/vault/keys/:provider',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Deletes a provider key.',
      },
      {
        method: 'POST',
        path: '/v1/vault/keys/:provider/rotate',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Rotates a provider key.',
      },
      {
        method: 'POST',
        path: '/v1/vault/keys/:provider/validate',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Validates a provider key with the current backend implementation.',
      },
      {
        method: 'GET',
        path: '/v1/policy',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Returns tenant policy document.',
      },
      {
        method: 'PUT',
        path: '/v1/policy',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Replaces tenant policy document.',
      },
      {
        method: 'GET',
        path: '/v1/policy/history',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Returns tenant policy history.',
      },
    ],
  },
  {
    title: 'Execution, History, and Receipts',
    summary:
      'Supported audit and receipt endpoints for customer-visible history and proof verification.',
    endpoints: [
      {
        method: 'GET',
        path: '/v1/history/events',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Lists execution history events. Supports `range`, `limit`, `agent_id`, and `device_id`.',
      },
      {
        method: 'GET',
        path: '/v1/receipts',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Lists execution receipts from the coordination layer.',
      },
      {
        method: 'GET',
        path: '/v1/receipts/:id',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Gets a single execution receipt by execution ID.',
      },
      {
        method: 'GET',
        path: '/v1/receipts/export',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Exports receipts as JSONL or CSV.',
      },
      {
        method: 'POST',
        path: '/proof/receipts/verify',
        auth: 'Session cookie or igris_ API key',
        surface: 'Proof API',
        stability: 'stable',
        description: 'Verifies a receipt signature and chain integrity.',
      },
    ],
  },
  {
    title: 'Behavior Trees',
    summary:
      'Supported behavior-tree definition endpoints exposed by the coordination layer.',
    endpoints: [
      {
        method: 'GET',
        path: '/v1/bt/templates',
        auth: 'Public',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Lists built-in behavior-tree templates.',
      },
      {
        method: 'GET',
        path: '/v1/bt/definitions',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Lists tenant behavior-tree definitions.',
      },
      {
        method: 'GET',
        path: '/v1/bt/definitions/:id',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Gets a single behavior-tree definition.',
      },
      {
        method: 'POST',
        path: '/v1/bt/definitions',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Creates or upserts a behavior-tree definition.',
      },
      {
        method: 'DELETE',
        path: '/v1/bt/definitions/:id',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Deletes a behavior-tree definition.',
      },
    ],
  },
  {
    title: 'Durable Tasks',
    summary:
      'Submit durable workflows and long-running tasks that preserve progress automatically across runtime interruptions.',
    endpoints: [
      {
        method: 'POST',
        path: '/v1/tasks/submit',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Submit a durable task using `agent_workflow`, `robotics_workflow`, `single_inference`, or `behavior_tree`.',
      },
      {
        method: 'GET',
        path: '/v1/tasks/:id',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Poll the current status and latest checkpoint metadata for a durable task.',
      },
      {
        method: 'GET',
        path: '/v1/tasks',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'List recent durable tasks for the authenticated tenant.',
      },
    ],
  },
  {
    title: 'Local Runtime API',
    summary:
      'Supported endpoints served by `igris-runtime` on the local runtime instance.',
    endpoints: [
      {
        method: 'GET',
        path: '/v1/health',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'stable',
        description: 'Health check for the local runtime.',
      },
      {
        method: 'POST',
        path: '/v1/chat/completions',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'stable',
        description: 'OpenAI-compatible local inference endpoint.',
      },
      {
        method: 'POST',
        path: '/v1/plan',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'stable',
        description: 'Planning endpoint.',
      },
      {
        method: 'POST',
        path: '/v1/reflect',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'stable',
        description: 'Reflection endpoint.',
      },
      {
        method: 'GET',
        path: '/v1/admin/models',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'preview',
        description: 'Lists loaded local models.',
      },
      {
        method: 'POST',
        path: '/v1/admin/models/load',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'preview',
        description: 'Loads a local model.',
      },
      {
        method: 'POST',
        path: '/v1/admin/models/swap',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'preview',
        description: 'Swaps the active local model.',
      },
      {
        method: 'POST',
        path: '/v1/btree/validate',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'stable',
        description: 'Validates a runtime behavior tree definition.',
      },
      {
        method: 'POST',
        path: '/v1/btree/run',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'stable',
        description: 'Executes a runtime behavior tree.',
      },
      {
        method: 'POST',
        path: '/v1/btree/deploy',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'stable',
        description: 'Deploys a runtime behavior tree.',
      },
      {
        method: 'GET',
        path: '/v1/btree/events',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'stable',
        description: 'Streams behavior-tree events.',
      },
    ],
  },
];

const bannedPatterns = [
  { pattern: /@igris\/sdk/, message: 'Use @igris-inertial/sdk for the JavaScript SDK.' },
  { pattern: /github\.com\/igris\/go-sdk/, message: 'Use github.com/igris-inertial/go-sdk for the Go SDK.' },
  { pattern: /Authorization:\s+Bearer\s+YOUR_SESSION_TOKEN/, message: 'Console session auth is cookie-based; do not document Bearer session tokens.' },
  { pattern: /igris_sk_/, message: 'Generated tenant API keys use the igris_ prefix, not igris_sk_.' },
  { pattern: /\/api\/v1\/runtime\/instances/, message: 'Use /api/v1/runtime/list.' },
  { pattern: /\blocal_inference\b/, message: 'Use local_fallback in runtime configuration docs.' },
  { pattern: /\bmax_context_length\b/, message: 'Use context_size in runtime configuration docs.' },
  { pattern: /\bgpu_layers\b/, message: 'Use n_gpu_layers in runtime configuration docs.' },
  { pattern: /\bfallback_only\b/, message: 'Do not document unsupported fallback_only config.' },
];

module.exports = {
  apiSections,
  bannedPatterns,
  docsAppRoot,
  docsDir,
  generatedDir,
  repoRoot,
  sdkSupport,
};
