const path = require('path');

const docsAppRoot = path.resolve(__dirname, '..');
const repoRoot = path.resolve(docsAppRoot, '../../..');
const docsDir = path.join(docsAppRoot, 'content', 'docs');
const generatedDir = path.join(docsAppRoot, 'lib', 'generated');

const sdkSupport = {
  generated_by: 'scripts/generate-docs-artifacts.js',
  native_sdk_note:
    'Recommended onboarding starts with the OpenAI-compatible API. When you need native Igris features, the first-class SDKs are JavaScript/TypeScript, Go, Rust, and Python. Java, C#, and Ruby should use an OpenAI-compatible client today.',
  rows: [
    {
      language: 'JavaScript / TypeScript',
      status: 'first-class',
      package: '@igris-inertial/sdk',
      install: 'npm install @igris-inertial/sdk',
      import: "import { IgrisClient } from '@igris-inertial/sdk';",
      notes: 'Preferred native SDK for browser and Node.js integrations.',
    },
    {
      language: 'Go',
      status: 'first-class',
      package: 'github.com/igris-inertial/go-sdk',
      install: 'go get github.com/igris-inertial/go-sdk',
      import: 'import igris "github.com/igris-inertial/go-sdk"',
      notes: 'Preferred native SDK for backend services and CLI tooling.',
    },
    {
      language: 'Rust',
      status: 'first-class',
      package: 'igris-inertial',
      install: 'cargo add igris-inertial',
      import: 'use igris_inertial::IgrisClient;',
      notes: 'Preferred native SDK for systems and embedded integrations.',
    },
    {
      language: 'Python',
      status: 'first-class',
      package: 'igris-inertial',
      install: 'pip install igris-inertial',
      import: 'from igris import IgrisClient',
      notes: 'Preferred native SDK for Python services, data pipelines, and scripting.',
    },
    {
      language: 'Java',
      status: 'openai-compatible',
      package: 'n/a',
      install: 'Use an OpenAI-compatible client today',
      import: 'Use the OpenAI-compatible base URL',
      notes: 'Use the OpenAI-compatible API until a native Java SDK is promoted explicitly.',
    },
    {
      language: 'C#',
      status: 'openai-compatible',
      package: 'n/a',
      install: 'Use an OpenAI-compatible client today',
      import: 'Use the OpenAI-compatible base URL',
      notes: 'Use the OpenAI-compatible API until a native C# SDK is promoted explicitly.',
    },
    {
      language: 'Ruby',
      status: 'openai-compatible',
      package: 'n/a',
      install: 'Use an OpenAI-compatible client today',
      import: 'Use the OpenAI-compatible base URL',
      notes: 'Use the OpenAI-compatible API until a native Ruby SDK is promoted explicitly.',
    },
  ],
};

const mcpReference = {
  overview: {
    title: 'MCP',
    summary:
      'The MCP surface in Igris for structured shared context, tool-oriented state exchange, and cross-runtime coordination.',
  },
  guides: [
    {
      slug: 'mcp',
      title: 'Overview',
      href: '/docs/mcp',
      summary: 'What MCP does in Igris, where it fits in the product, and which transport surfaces expose it.',
    },
    {
      slug: 'mcp-server',
      title: 'MCP Server',
      href: '/docs/mcp-server',
      summary: 'The product-facing MCP server contract, JSON-RPC request shape, and core method families.',
    },
    {
      slug: 'mcp-swarm',
      title: 'MCP Swarm Mode',
      href: '/docs/mcp-swarm',
      summary: 'How shared context replication works across multiple runtimes and where its design boundaries are.',
    },
    {
      slug: 'mcp-integration-patterns',
      title: 'MCP Integration Patterns',
      href: '/docs/mcp-integration-patterns',
      summary: 'How to use MCP in production without confusing shared context, durable progress, and audit evidence.',
    },
  ],
  methodGroups: [
    {
      title: 'Transport Surfaces',
      summary: 'Customer-facing routes that carry MCP traffic through the product.',
      methods: [
        {
          name: 'POST /v1/mcp',
          kind: 'transport',
          page: '/docs/mcp#transport-surfaces',
          summary: 'Request/response JSON-RPC transport for MCP calls.',
        },
        {
          name: 'POST /v1/mcp/stream',
          kind: 'transport',
          page: '/docs/mcp#transport-surfaces',
          summary: 'Streaming transport for MCP interactions that return incremental events.',
        },
      ],
    },
    {
      title: 'Context Methods',
      summary: 'Methods for structured shared context rather than one-off prompt state.',
      methods: [
        {
          name: 'context/write',
          kind: 'method',
          page: '/docs/mcp-server#core-method-families',
          summary: 'Write a structured value into shared MCP context.',
        },
        {
          name: 'context/read',
          kind: 'method',
          page: '/docs/mcp-server#core-method-families',
          summary: 'Read a context value by key.',
        },
        {
          name: 'context/list',
          kind: 'method',
          page: '/docs/mcp-server#core-method-families',
          summary: 'List available shared-context keys.',
        },
        {
          name: 'context/delete',
          kind: 'method',
          page: '/docs/mcp-server#core-method-families',
          summary: 'Delete a context value by key.',
        },
      ],
    },
    {
      title: 'Tool Methods',
      summary: 'Methods for discovery and invocation of MCP-exposed tools.',
      methods: [
        {
          name: 'tools/list',
          kind: 'method',
          page: '/docs/mcp-server#core-method-families',
          summary: 'List tools exposed through the MCP server.',
        },
        {
          name: 'tools/call',
          kind: 'method',
          page: '/docs/mcp-server#core-method-families',
          summary: 'Call a tool through the MCP server contract.',
        },
      ],
    },
  ],
};

const rawApiSections = [
  {
    title: 'Inference & Integration',
    summary:
      'Supported cloud inference endpoints. `/v1/chat/completions` is OpenAI-compatible, while `/v1/infer` exposes the native Igris request contract.',
    endpoints: [
      {
        method: 'POST',
        path: '/v1/infer',
        auth: 'Deployment-dependent',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Native inference endpoint handled by Overture.',
      },
      {
        method: 'POST',
        path: '/v1/chat/completions',
        auth: 'Deployment-dependent',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'OpenAI-compatible chat completions endpoint.',
      },
      {
        method: 'GET',
        path: '/v1/health',
        auth: 'Public',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Health check for inference availability.',
      },
      {
        method: 'GET',
        path: '/v1/models',
        auth: 'Public',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Lists models visible to the inference layer.',
      },
      {
        method: 'GET',
        path: '/v1/providers/stats',
        auth: 'Public',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Provider latency, health, and routing statistics.',
      },
      {
        method: 'POST',
        path: '/v1/infer/multimodal',
        auth: 'Session or API key',
        surface: 'Cloud API',
        stability: 'preview',
        description: 'Multimodal inference endpoint.',
      },
      {
        method: 'GET',
        path: '/v1/infer/multimodal/stats',
        auth: 'Session or API key',
        surface: 'Cloud API',
        stability: 'preview',
        description: 'Multimodal request statistics.',
      },
    ],
  },
  {
    title: 'Runtime Distribution & Fleet Coordination',
    summary:
      'Supported endpoints for downloading `igris-runtime`, registering runtime instances, and managing fleet operations from the control plane.',
    endpoints: [
      {
        method: 'GET',
        path: '/v1/runtime/install',
        auth: 'Public',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Returns or redirects to the platform-specific runtime archive.',
      },
      {
        method: 'GET',
        path: '/v1/runtime/checksum',
        auth: 'Public',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Returns the SHA-256 checksum for a runtime archive.',
      },
      {
        method: 'GET',
        path: '/v1/runtime/download',
        auth: 'Session or API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Subscribed runtime binary download endpoint.',
      },
      {
        method: 'GET',
        path: '/api/v1/runtime/download',
        auth: 'igris_ API key via X-API-Key or Authorization: Bearer',
        surface: 'Fleet management',
        stability: 'stable',
        description: 'API-key authenticated runtime binary download endpoint for runtime installers.',
      },
      {
        method: 'POST',
        path: '/api/v1/runtime/register',
        auth: 'igris_ API key via X-API-Key or Authorization: Bearer',
        surface: 'Fleet management',
        stability: 'stable',
        description: 'Registers a runtime instance with the hosted control plane.',
      },
      {
        method: 'POST',
        path: '/api/v1/runtime/heartbeat',
        auth: 'igris_ API key via X-API-Key or Authorization: Bearer',
        surface: 'Fleet management',
        stability: 'stable',
        description: 'Refreshes runtime liveness and reports whether commands are pending.',
      },
      {
        method: 'GET',
        path: '/api/v1/runtime/commands',
        auth: 'igris_ API key via X-API-Key or Authorization: Bearer',
        surface: 'Fleet management',
        stability: 'stable',
        description: 'Fetches and clears queued commands for a registered runtime.',
      },
      {
        method: 'DELETE',
        path: '/api/v1/runtime/deregister',
        auth: 'igris_ API key via X-API-Key or Authorization: Bearer',
        surface: 'Fleet management',
        stability: 'stable',
        description: 'Marks a runtime instance as deregistered.',
      },
      {
        method: 'GET',
        path: '/api/v1/runtime/list',
        auth: 'tenant_id query or authenticated tenant context',
        surface: 'Fleet management',
        stability: 'stable',
        description: 'Lists registered runtime instances for a tenant.',
      },
      {
        method: 'POST',
        path: '/api/v1/runtime/config/push',
        auth: 'Session cookie',
        surface: 'Fleet management',
        stability: 'stable',
        description: 'Queues configuration push commands for the fleet.',
      },
      {
        method: 'POST',
        path: '/api/v1/runtime/update',
        auth: 'Session cookie',
        surface: 'Fleet management',
        stability: 'stable',
        description: 'Queues OTA update commands for the fleet.',
      },
    ],
  },
  {
    title: 'Account, Trial, and Billing',
    summary:
      'Supported account and billing endpoints for subscription state and tenant API key lifecycle management.',
    endpoints: [
      {
        method: 'GET',
        path: '/api/subscription/status',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Returns subscription tier, status, and runtime usage.',
      },
      {
        method: 'GET',
        path: '/api/subscription/plans',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Lists available plans and checkout URLs.',
      },
      {
        method: 'GET',
        path: '/v1/account/api-key',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Returns current API key metadata without revealing the secret.',
      },
      {
        method: 'POST',
        path: '/v1/account/api-key',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Creates a new tenant API key and revokes the old one.',
      },
      {
        method: 'DELETE',
        path: '/v1/account/api-key',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Revokes the current tenant API key.',
      },
    ],
  },
  {
    title: 'Vault, Policy, and Governance',
    summary:
      'Supported BYOK and tenant policy routes.',
    endpoints: [
      {
        method: 'GET',
        path: '/v1/vault/keys',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Lists configured provider keys with masked values.',
      },
      {
        method: 'POST',
        path: '/v1/vault/keys',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Stores a provider key using `{ provider, key_name, api_key }`.',
      },
      {
        method: 'GET',
        path: '/v1/vault/keys/:provider',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Gets a single provider key record.',
      },
      {
        method: 'DELETE',
        path: '/v1/vault/keys/:provider',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Deletes a provider key.',
      },
      {
        method: 'POST',
        path: '/v1/vault/keys/:provider/rotate',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Rotates a provider key.',
      },
      {
        method: 'POST',
        path: '/v1/vault/keys/:provider/validate',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Validates a provider key with the current backend implementation.',
      },
      {
        method: 'GET',
        path: '/v1/policy',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Returns tenant policy document.',
      },
      {
        method: 'PUT',
        path: '/v1/policy',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Replaces tenant policy document.',
      },
      {
        method: 'GET',
        path: '/v1/policy/history',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Returns tenant policy history.',
      },
    ],
  },
  {
    title: 'Execution, History, and Receipts',
    summary:
      'Supported audit and receipt endpoints for customer-visible history and proof verification.',
    endpoints: [
      {
        method: 'GET',
        path: '/v1/history/events',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Lists execution history events. Supports `range`, `limit`, `agent_id`, and `device_id`.',
      },
      {
        method: 'GET',
        path: '/v1/receipts',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Lists execution receipts from the coordination layer.',
      },
      {
        method: 'GET',
        path: '/v1/receipts/:id',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Gets a single execution receipt by execution ID.',
      },
      {
        method: 'GET',
        path: '/v1/receipts/export',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Exports receipts as JSONL or CSV.',
      },
      {
        method: 'POST',
        path: '/proof/receipts/verify',
        auth: 'Session cookie or igris_ API key',
        surface: 'Proof API',
        stability: 'stable',
        description: 'Verifies a receipt signature and chain integrity.',
      },
    ],
  },
  {
    title: 'Routing Control & Analytics',
    summary:
      'Customer-visible routing controls and read models for adaptive routing, speculative execution, council mode, provider weighting, and circuit-breaker state.',
    endpoints: [
      {
        method: 'GET',
        path: '/v1/routing/stats',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Returns aggregate routing request and latency statistics.',
      },
      {
        method: 'GET',
        path: '/v1/routing/recent',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Lists recent routed requests for operational inspection.',
      },
      {
        method: 'GET',
        path: '/v1/routing/leaderboard',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Ranks providers by recent routing performance.',
      },
      {
        method: 'POST',
        path: '/v1/routing/strategy',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Saves the tenant routing strategy configuration.',
      },
      {
        method: 'POST',
        path: '/v1/routing/provider_weights',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Saves tenant provider weight overrides.',
      },
      {
        method: 'GET',
        path: '/v1/routing/speculative/status',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Returns current speculative-routing status metrics.',
      },
      {
        method: 'GET',
        path: '/v1/routing/speculative/config',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Returns the active speculative-routing configuration read model.',
      },
      {
        method: 'POST',
        path: '/v1/routing/speculative',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Saves tenant speculative-routing configuration.',
      },
      {
        method: 'GET',
        path: '/v1/routing/speculative/analytics',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Returns speculative-routing analytics series.',
      },
      {
        method: 'POST',
        path: '/v1/routing/speculative/simulate',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'preview',
        description: 'Triggers a speculative-routing simulation for a sample request.',
      },
      {
        method: 'POST',
        path: '/v1/routing/council',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Saves tenant council-mode routing configuration.',
      },
      {
        method: 'GET',
        path: '/v1/routing/council/analytics',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Returns council-mode aggregate and per-chairman analytics.',
      },
      {
        method: 'POST',
        path: '/v1/routing/shadow',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Saves tenant shadow-routing configuration.',
      },
      {
        method: 'GET',
        path: '/v1/routing/circuit-breaker/status',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Returns aggregate and per-provider circuit-breaker state.',
      },
    ],
  },
  {
    title: 'Behavior Trees',
    summary:
      'Supported behavior-tree definition endpoints exposed by the coordination layer.',
    endpoints: [
      {
        method: 'GET',
        path: '/v1/bt/templates',
        auth: 'Public',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Lists built-in behavior-tree templates.',
      },
      {
        method: 'GET',
        path: '/v1/bt/definitions',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Lists tenant behavior-tree definitions.',
      },
      {
        method: 'GET',
        path: '/v1/bt/definitions/:id',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Gets a single behavior-tree definition.',
      },
      {
        method: 'POST',
        path: '/v1/bt/definitions',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Creates or upserts a behavior-tree definition.',
      },
      {
        method: 'DELETE',
        path: '/v1/bt/definitions/:id',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Deletes a behavior-tree definition.',
      },
    ],
  },
  {
    title: 'Durable Tasks',
    summary:
      'Submit durable workflows and long-running tasks that preserve progress automatically across runtime interruptions.',
    endpoints: [
      {
        method: 'POST',
        path: '/v1/tasks/submit',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Submit a durable task using `agent_workflow`, `robotics_workflow`, `single_inference`, or `behavior_tree`.',
      },
      {
        method: 'GET',
        path: '/v1/tasks/:id',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Poll the current status and latest checkpoint metadata for a durable task.',
      },
      {
        method: 'GET',
        path: '/v1/tasks',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'List recent durable tasks for the authenticated tenant.',
      },
      {
        method: 'GET',
        path: '/v1/tasks/:id/steps',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Lists execution-graph steps and graph slots for a durable task when available.',
      },
      {
        method: 'POST',
        path: '/v1/tasks/:id/cancel',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Requests cancellation for a non-terminal durable task.',
      },
      {
        method: 'GET',
        path: '/v1/tasks/proof/readiness',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Reports whether trigger-backed proof synchronization is active.',
      },
      {
        method: 'POST',
        path: '/v1/tasks/:id/proof/verify',
        auth: 'Session cookie or igris_ API key',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Synchronizes and verifies persisted proof state for a durable task.',
      },
    ],
  },
  {
    title: 'MCP Transport',
    summary:
      'Hosted MCP transport routes for structured shared context and tool-oriented workflows.',
    endpoints: [
      {
        method: 'POST',
        path: '/v1/mcp',
        auth: 'Deployment-dependent',
        surface: 'Cloud API',
        stability: 'stable',
        description: 'Forwards JSON-RPC MCP requests to the configured runtime MCP server.',
      },
      {
        method: 'POST',
        path: '/v1/mcp/stream',
        auth: 'Deployment-dependent',
        surface: 'Cloud API',
        stability: 'preview',
        description: 'Forwards streaming MCP requests to the configured runtime MCP server.',
      },
    ],
  },
  {
    title: 'Local Runtime API',
    summary:
      'Supported endpoints served by `igris-runtime` on the local runtime instance.',
    endpoints: [
      {
        method: 'GET',
        path: '/v1/health',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'stable',
        description: 'Health check for the local runtime.',
      },
      {
        method: 'GET',
        path: '/v1/runtime/profile',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'stable',
        description: 'Returns local runtime capability and feature profile.',
      },
      {
        method: 'POST',
        path: '/v1/chat/completions',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'stable',
        description: 'OpenAI-compatible local inference endpoint.',
      },
      {
        method: 'POST',
        path: '/v1/plan',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'stable',
        description: 'Planning endpoint.',
      },
      {
        method: 'POST',
        path: '/v1/reflect',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'stable',
        description: 'Reflection endpoint.',
      },
      {
        method: 'GET',
        path: '/v1/admin/models',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'preview',
        description: 'Lists loaded local models.',
      },
      {
        method: 'POST',
        path: '/v1/admin/models/load',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'preview',
        description: 'Loads a local model.',
      },
      {
        method: 'POST',
        path: '/v1/admin/models/swap',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'preview',
        description: 'Swaps the active local model.',
      },
      {
        method: 'POST',
        path: '/v1/btree/validate',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'stable',
        description: 'Validates a runtime behavior tree definition.',
      },
      {
        method: 'POST',
        path: '/v1/btree/run',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'stable',
        description: 'Executes a runtime behavior tree.',
      },
      {
        method: 'POST',
        path: '/v1/btree/deploy',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'stable',
        description: 'Deploys a runtime behavior tree.',
      },
      {
        method: 'GET',
        path: '/v1/btree/events',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'stable',
        description: 'Streams behavior-tree events.',
      },
      {
        method: 'GET',
        path: '/v1/lora/status',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'preview',
        description: 'Returns local LoRA training and adapter status.',
      },
      {
        method: 'GET',
        path: '/v1/memory/status',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'stable',
        description: 'Returns local memory subsystem status.',
      },
      {
        method: 'POST',
        path: '/v1/memory/store',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'stable',
        description: 'Stores an item in local runtime memory.',
      },
      {
        method: 'POST',
        path: '/v1/memory/search',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'stable',
        description: 'Searches local runtime memory.',
      },
      {
        method: 'GET',
        path: '/v1/memory/:key',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'stable',
        description: 'Reads one item from local runtime memory by key.',
      },
      {
        method: 'GET',
        path: '/v1/hitl/status',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'preview',
        description: 'Returns local human-in-the-loop queue status.',
      },
      {
        method: 'GET',
        path: '/v1/hitl/requests',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'preview',
        description: 'Lists local human-in-the-loop approval requests.',
      },
      {
        method: 'POST',
        path: '/v1/hitl/request',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'preview',
        description: 'Creates a local human-in-the-loop approval request.',
      },
      {
        method: 'POST',
        path: '/v1/hitl/approve',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'preview',
        description: 'Approves a local human-in-the-loop request.',
      },
      {
        method: 'POST',
        path: '/v1/hitl/reject',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'preview',
        description: 'Rejects a local human-in-the-loop request.',
      },
      {
        method: 'GET',
        path: '/v1/swarm/status',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'preview',
        description: 'Returns local swarm coordination status.',
      },
      {
        method: 'GET',
        path: '/v1/swarm/agents',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'preview',
        description: 'Lists local swarm agents.',
      },
      {
        method: 'POST',
        path: '/v1/swarm/join',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'preview',
        description: 'Joins the local runtime to a swarm.',
      },
      {
        method: 'POST',
        path: '/v1/swarm/propose',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'preview',
        description: 'Submits a swarm proposal.',
      },
      {
        method: 'POST',
        path: '/v1/swarm/vote',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'preview',
        description: 'Submits a swarm vote.',
      },
      {
        method: 'GET',
        path: '/v1/federated/status',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'preview',
        description: 'Returns local federated-learning status.',
      },
      {
        method: 'POST',
        path: '/v1/federated/update',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'preview',
        description: 'Submits a local federated-learning model update.',
      },
      {
        method: 'GET',
        path: '/v1/federated/model/latest',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'preview',
        description: 'Returns metadata for the latest local federated model.',
      },
      {
        method: 'GET',
        path: '/v1/federated/participants',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'preview',
        description: 'Lists local federated-learning participants.',
      },
      {
        method: 'POST',
        path: '/v1/runtime/execute',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'stable',
        description: 'Executes a runtime task through the local execution boundary.',
      },
      {
        method: 'GET',
        path: '/v1/runtime/violations',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'stable',
        description: 'Lists local runtime execution violations.',
      },
      {
        method: 'POST',
        path: '/v1/runtime/task/submit',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'stable',
        description: 'Submits a durable task directly to the local runtime executor.',
      },
      {
        method: 'POST',
        path: '/v1/runtime/task/stream',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'stable',
        description: 'Submits a streaming durable task directly to the local runtime executor.',
      },
      {
        method: 'POST',
        path: '/v1/runtime/task/{task_id}/cancel',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'stable',
        description: 'Cancels a local runtime durable task.',
      },
      {
        method: 'GET',
        path: '/v1/runtime/task/{task_id}/wal',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'stable',
        description: 'Reads the local WAL entries for a runtime durable task.',
      },
      {
        method: 'GET',
        path: '/v1/runtime/agent/:id/state',
        auth: 'Runtime-config dependent',
        surface: 'Local runtime',
        stability: 'preview',
        description: 'Returns the local runtime state for one agent.',
      },
    ],
  },
];

const coreEndpointKeys = new Set([
  'POST /v1/infer',
  'POST /v1/chat/completions',
  'GET /v1/models',
  'GET /v1/runtime/install',
  'GET /v1/runtime/checksum',
  'GET /v1/account/api-key',
  'POST /v1/account/api-key',
  'GET /v1/vault/keys',
  'POST /v1/vault/keys',
  'GET /v1/receipts',
  'GET /v1/receipts/:id',
  'GET /v1/health',
  'POST /v1/btree/validate',
  'POST /v1/btree/run',
]);

function endpointKey(endpoint) {
  return `${endpoint.method} ${endpoint.path}`;
}

function inferDeployment(endpoint) {
  if (endpoint.surface === 'Local runtime') {
    return 'local';
  }

  if (endpoint.path.startsWith('/v1/runtime/') || endpoint.path.startsWith('/api/v1/runtime/')) {
    return 'hybrid';
  }

  return 'cloud';
}

function inferSupport(endpoint) {
  if (endpoint.stability === 'preview') {
    return 'preview';
  }

  if (coreEndpointKeys.has(endpointKey(endpoint))) {
    return 'core';
  }

  return 'supported';
}

const apiSections = rawApiSections.map((section) => ({
  ...section,
  endpoints: section.endpoints.map((endpoint) => ({
    ...endpoint,
    support: endpoint.support ?? inferSupport(endpoint),
    deployment: endpoint.deployment ?? inferDeployment(endpoint),
  })),
}));

const bannedPatterns = [
  { pattern: /@igris\/sdk/, message: 'Use @igris-inertial/sdk for the JavaScript SDK.' },
  { pattern: /github\.com\/igris\/go-sdk/, message: 'Use github.com/igris-inertial/go-sdk for the Go SDK.' },
  { pattern: /Authorization:\s+Bearer\s+YOUR_SESSION_TOKEN/, message: 'Console session auth is cookie-based; do not document Bearer session tokens.' },
  { pattern: /igris_sk_/, message: 'Generated tenant API keys use the igris_ prefix, not igris_sk_.' },
  { pattern: /\/api\/v1\/runtime\/instances/, message: 'Use /api/v1/runtime/list.' },
  { pattern: /\blocal_inference\b/, message: 'Use local_fallback in runtime configuration docs.' },
  { pattern: /\bmax_context_length\b/, message: 'Use context_size in runtime configuration docs.' },
  { pattern: /\bgpu_layers\b/, message: 'Use n_gpu_layers in runtime configuration docs.' },
  { pattern: /\bfallback_only\b/, message: 'Do not document unsupported fallback_only config.' },
  { pattern: /\/v1\/slo\/config/, message: 'Do not document unsupported /v1/slo/config routes; use the SLO Enforcer guide current-contract language.' },
  { pattern: /\/v1\/slo\/compliance/, message: 'Do not document unsupported /v1/slo/compliance routes; use routing, receipts, and observability surfaces.' },
  { pattern: /\bdraft_would_accept\b/, message: 'Speculative simulation currently returns { simulated, message }; do not document planned predictor fields as current output.' },
  { pattern: /\bcurrently_active\b/, message: 'Speculative status currently returns enabled, success_rate, latency_improvement_ms, cost_delta_percent, races_24h, and wins_by_provider.' },
  { pattern: /\b(customer|tenant)\s+webhook\s+(management|endpoints?|configuration|settings)\b/i, message: 'Do not present customer webhook management as shipped unless the codebase exposes the route and schema.' },
  { pattern: /\b(webhook\s+management|manage\s+webhooks|configured\s+webhooks)\b/i, message: 'Do not present customer webhook management as shipped unless the codebase exposes the route and schema.' },
  { pattern: /\/(?:api\/)?v1\/webhooks\b/i, message: 'Do not document webhook management routes unless they are implemented and audited.' },
  { pattern: /\b(local|runtime)\s+receipt\s+listing\s+(is available|api|route lets|endpoint returns|endpoint lists)\b/i, message: 'Runtime does not expose a public local receipt listing endpoint; use cloud receipt routes or execution response receipts.' },
  { pattern: /\/v1\/(?:runtime|local)\/receipts\b/i, message: 'Runtime/local receipt listing routes are not implemented; use /v1/receipts on the coordination layer.' },
  { pattern: /(?:\/v1)?\/emergency-stop\b/i, message: 'Do not document an emergency-stop HTTP endpoint unless it is implemented and audited.' },
  { pattern: /\bemergency-stop HTTP endpoint\b/i, message: 'Do not document an emergency-stop HTTP endpoint unless it is implemented and audited.' },
  { pattern: /\bclient\.streamInference\s*\(/, message: 'The JavaScript SDK does not expose client.streamInference(); document implemented streaming surfaces only.' },
  { pattern: /\bSDK streaming helpers?\s+(is|are)\s+(available|implemented)\b/i, message: 'Do not present SDK streaming helpers as implemented unless the SDK exposes them and snippets compile.' },
];

module.exports = {
  apiSections,
  bannedPatterns,
  docsAppRoot,
  docsDir,
  generatedDir,
  mcpReference,
  repoRoot,
  sdkSupport,
};
