// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: adapters/python/python_ml/proto/ml_service.proto

package ml

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PredictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Features      []float64              `protobuf:"fixed64,1,rep,packed,name=features,proto3" json:"features,omitempty"`
	ModelId       string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_adapters_python_python_ml_proto_ml_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adapters_python_python_ml_proto_ml_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_adapters_python_python_ml_proto_ml_service_proto_rawDescGZIP(), []int{0}
}

func (x *PredictRequest) GetFeatures() []float64 {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *PredictRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type PredictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prediction    float64                `protobuf:"fixed64,1,opt,name=prediction,proto3" json:"prediction,omitempty"`
	Confidence    float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ModelId       string                 `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_adapters_python_python_ml_proto_ml_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adapters_python_python_ml_proto_ml_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_adapters_python_python_ml_proto_ml_service_proto_rawDescGZIP(), []int{1}
}

func (x *PredictResponse) GetPrediction() float64 {
	if x != nil {
		return x.Prediction
	}
	return 0
}

func (x *PredictResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *PredictResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_adapters_python_python_ml_proto_ml_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adapters_python_python_ml_proto_ml_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_adapters_python_python_ml_proto_ml_service_proto_rawDescGZIP(), []int{2}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_adapters_python_python_ml_proto_ml_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adapters_python_python_ml_proto_ml_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_adapters_python_python_ml_proto_ml_service_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_adapters_python_python_ml_proto_ml_service_proto protoreflect.FileDescriptor

const file_adapters_python_python_ml_proto_ml_service_proto_rawDesc = "" +
	"\n" +
	"0adapters/python/python_ml/proto/ml_service.proto\x12\x02ml\"G\n" +
	"\x0ePredictRequest\x12\x1a\n" +
	"\bfeatures\x18\x01 \x03(\x01R\bfeatures\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\"l\n" +
	"\x0fPredictResponse\x12\x1e\n" +
	"\n" +
	"prediction\x18\x01 \x01(\x01R\n" +
	"prediction\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\"\x14\n" +
	"\x12HealthCheckRequest\"G\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion2\x7f\n" +
	"\tMLService\x122\n" +
	"\aPredict\x12\x12.ml.PredictRequest\x1a\x13.ml.PredictResponse\x12>\n" +
	"\vHealthCheck\x12\x16.ml.HealthCheckRequest\x1a\x17.ml.HealthCheckResponseB1Z/github.com/Igris-inertial/system/proto/mlb\x06proto3"

var (
	file_adapters_python_python_ml_proto_ml_service_proto_rawDescOnce sync.Once
	file_adapters_python_python_ml_proto_ml_service_proto_rawDescData []byte
)

func file_adapters_python_python_ml_proto_ml_service_proto_rawDescGZIP() []byte {
	file_adapters_python_python_ml_proto_ml_service_proto_rawDescOnce.Do(func() {
		file_adapters_python_python_ml_proto_ml_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_adapters_python_python_ml_proto_ml_service_proto_rawDesc), len(file_adapters_python_python_ml_proto_ml_service_proto_rawDesc)))
	})
	return file_adapters_python_python_ml_proto_ml_service_proto_rawDescData
}

var file_adapters_python_python_ml_proto_ml_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_adapters_python_python_ml_proto_ml_service_proto_goTypes = []any{
	(*PredictRequest)(nil),      // 0: ml.PredictRequest
	(*PredictResponse)(nil),     // 1: ml.PredictResponse
	(*HealthCheckRequest)(nil),  // 2: ml.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 3: ml.HealthCheckResponse
}
var file_adapters_python_python_ml_proto_ml_service_proto_depIdxs = []int32{
	0, // 0: ml.MLService.Predict:input_type -> ml.PredictRequest
	2, // 1: ml.MLService.HealthCheck:input_type -> ml.HealthCheckRequest
	1, // 2: ml.MLService.Predict:output_type -> ml.PredictResponse
	3, // 3: ml.MLService.HealthCheck:output_type -> ml.HealthCheckResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_adapters_python_python_ml_proto_ml_service_proto_init() }
func file_adapters_python_python_ml_proto_ml_service_proto_init() {
	if File_adapters_python_python_ml_proto_ml_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_adapters_python_python_ml_proto_ml_service_proto_rawDesc), len(file_adapters_python_python_ml_proto_ml_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_adapters_python_python_ml_proto_ml_service_proto_goTypes,
		DependencyIndexes: file_adapters_python_python_ml_proto_ml_service_proto_depIdxs,
		MessageInfos:      file_adapters_python_python_ml_proto_ml_service_proto_msgTypes,
	}.Build()
	File_adapters_python_python_ml_proto_ml_service_proto = out.File
	file_adapters_python_python_ml_proto_ml_service_proto_goTypes = nil
	file_adapters_python_python_ml_proto_ml_service_proto_depIdxs = nil
}
