#!/bin/zsh

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
ROOT_DIR=$(cd "$SCRIPT_DIR/.." && pwd)
LOCAL_ENV_FILE="$ROOT_DIR/.env.run-recover-prove-local"
COMPOSE_FILE="$ROOT_DIR/docker-compose.run-recover-prove-local.yml"
DB_NAME="${IGRIS_LOCAL_POSTGRES_DB:-igris_overture}"
DB_USER="${IGRIS_LOCAL_POSTGRES_USER:-igris_user}"
DB_PORT="${IGRIS_LOCAL_POSTGRES_PORT:-55432}"
MODE="${1:-run}"
PROVISION_PATH="unknown"

if [[ ! "$DB_NAME" =~ '^[A-Za-z0-9_]+$' || ! "$DB_USER" =~ '^[A-Za-z0-9_]+$' || ! "$DB_PORT" =~ '^[0-9]+$' ]]; then
  echo "requirement failed: IGRIS_LOCAL_POSTGRES_DB, IGRIS_LOCAL_POSTGRES_USER, and IGRIS_LOCAL_POSTGRES_PORT must be simple local identifiers." >&2
  exit 1
fi

usage() {
  cat >&2 <<'EOF'
usage: scripts/igris-local-provision.sh [run|up|down|reset]

  run    provision Postgres, migrate, doctor, then run the full live demo
  up     provision Postgres, migrate, and doctor only
  down   stop Docker-managed local services without deleting data
  reset  delete Docker-managed local Postgres data and local generated env
EOF
}

case "$MODE" in
  run|up|down|reset) ;;
  *) usage; exit 2 ;;
esac

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "missing required command: $1" >&2
    case "$1" in
      psql) echo "fix: install the PostgreSQL client (macOS: brew install libpq && brew link --force libpq, or brew install postgresql@16)" >&2 ;;
      node) echo "fix: install Node 20+ and ensure node is on PATH" >&2 ;;
      make) echo "fix: install make and ensure make is on PATH" >&2 ;;
    esac
    exit 1
  }
}

sanitize_db_summary() {
  local raw="${1:-}"
  DB_URL="$raw" node - <<'NODE'
const raw = process.env.DB_URL || "";
try {
  const u = new URL(raw);
  const database = (u.pathname || "").replace(/^\//, "") || "";
  const port = u.port || "default";
  console.log(`  database:        ${u.protocol.replace(":", "")}://${u.hostname || "localhost"}:${port}/${database}`);
  console.log(`  db auth:         user=${u.username ? "set" : "unset"}, password=${u.password ? "set" : "unset"}, sslmode=${u.searchParams.get("sslmode") || "default"}`);
} catch (_) {
  console.log("  database:        invalid URL syntax");
}
NODE
}

source_env_if_present() {
  if [[ -f "$LOCAL_ENV_FILE" ]]; then
    set -a
    source "$LOCAL_ENV_FILE" >/dev/null 2>&1 || true
    set +a
  fi
}

docker_compose_available() {
  DOCKER_COMPOSE_CMD=()
  if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    DOCKER_COMPOSE_CMD=(docker compose)
  elif command -v docker-compose >/dev/null 2>&1 && docker-compose version >/dev/null 2>&1; then
    DOCKER_COMPOSE_CMD=(docker-compose)
  else
    return 1
  fi
  docker info >/dev/null 2>&1
}

write_docker_env_if_missing() {
  if [[ -f "$LOCAL_ENV_FILE" ]]; then
    return 0
  fi

  require_cmd node
  local password
  password=$(node -e 'process.stdout.write(require("crypto").randomBytes(24).toString("base64url"))')
  umask 077
  cat > "$LOCAL_ENV_FILE" <<EOF
# Local-only Run / Recover / Prove environment.
# Generated by scripts/igris-local-provision.sh. Do not commit.
POSTGRES_DB=$DB_NAME
POSTGRES_USER=$DB_USER
POSTGRES_PASSWORD=$password
POSTGRES_PORT=$DB_PORT
IGRIS_LOCAL_PROVISIONER=docker
DATABASE_URL=postgres://$DB_USER:$password@127.0.0.1:$DB_PORT/$DB_NAME?sslmode=disable
EOF
  chmod 600 "$LOCAL_ENV_FILE"
}

wait_for_database() {
  local db_url="$1"
  local label="$2"
  local attempt
  for attempt in {1..60}; do
    if psql "$db_url" -X -v ON_ERROR_STOP=1 -qtAc "SELECT 1" >/dev/null 2>&1; then
      return 0
    fi
    sleep 1
  done

  echo "requirement failed: timed out waiting for Postgres ($label)." >&2
  sanitize_db_summary "$db_url" >&2
  echo "fix: run make run-recover-prove-local-doctor for a sanitized diagnostic." >&2
  return 1
}

docker_up() {
  write_docker_env_if_missing
  source_env_if_present
  echo "[local-db] provisioning Postgres with Docker Compose"
  "${DOCKER_COMPOSE_CMD[@]}" --env-file "$LOCAL_ENV_FILE" -f "$COMPOSE_FILE" up -d postgres
  wait_for_database "$DATABASE_URL" "docker"
  PROVISION_PATH="Docker"
  echo "[local-db] Docker Postgres is ready"
  sanitize_db_summary "$DATABASE_URL"
}

homebrew_formula() {
  local formula
  for formula in postgresql@16 postgresql@15 postgresql@14 postgresql; do
    if brew list --versions "$formula" >/dev/null 2>&1; then
      echo "$formula"
      return 0
    fi
  done
  return 1
}

homebrew_up() {
  if [[ "$(uname -s)" != "Darwin" ]] || ! command -v brew >/dev/null 2>&1; then
    return 1
  fi

  local formula
  formula=$(homebrew_formula) || return 1

  echo "[local-db] Docker Compose is unavailable; trying Homebrew Postgres ($formula)"
  if command -v brew >/dev/null 2>&1 && brew services list >/dev/null 2>&1; then
    brew services start "$formula" >/dev/null || return 1
  fi

  require_cmd psql
  local postgres_url="postgres://${USER:-$(whoami)}@127.0.0.1:5432/postgres?sslmode=disable"
  wait_for_database "$postgres_url" "homebrew server" || return 1

  local exists
  exists=$(psql "$postgres_url" -X -tAqc "SELECT EXISTS (SELECT 1 FROM pg_database WHERE datname = '$DB_NAME');") || return 1
  if [[ "$exists" != "t" ]]; then
    if command -v createdb >/dev/null 2>&1; then
      createdb "$DB_NAME" || return 1
    else
      psql "$postgres_url" -X -v ON_ERROR_STOP=1 -qc "CREATE DATABASE \"$DB_NAME\"" || return 1
    fi
  fi

  local homebrew_db_url="postgres://${USER:-$(whoami)}@127.0.0.1:5432/$DB_NAME?sslmode=disable"
  wait_for_database "$homebrew_db_url" "homebrew database" || return 1

  umask 077
  cat > "$LOCAL_ENV_FILE" <<EOF
# Local-only Run / Recover / Prove environment.
# Generated by scripts/igris-local-provision.sh. Do not commit.
IGRIS_LOCAL_PROVISIONER=homebrew
DATABASE_URL=$homebrew_db_url
EOF
  chmod 600 "$LOCAL_ENV_FILE"
  source_env_if_present
  PROVISION_PATH="Homebrew"
  echo "[local-db] Homebrew Postgres is ready"
  sanitize_db_summary "$DATABASE_URL"
}

provision_up() {
  require_cmd make
  require_cmd node
  require_cmd psql

  if [[ -n "${DATABASE_URL:-${POSTGRES_URL:-}}" ]]; then
    PROVISION_PATH="existing Postgres"
    echo "[local-db] reusing DATABASE_URL/POSTGRES_URL from the current environment"
    sanitize_db_summary "${DATABASE_URL:-${POSTGRES_URL:-}}"
    wait_for_database "${DATABASE_URL:-${POSTGRES_URL:-}}" "existing"
    return 0
  fi

  source_env_if_present
  if [[ -n "${DATABASE_URL:-${POSTGRES_URL:-}}" ]]; then
    if [[ "${IGRIS_LOCAL_PROVISIONER:-}" == "docker" && docker_compose_available ]]; then
      docker_up
      return 0
    fi
    if [[ "${IGRIS_LOCAL_PROVISIONER:-}" == "homebrew" ]]; then
      homebrew_up
      return 0
    fi
    PROVISION_PATH="local env file"
    echo "[local-db] reusing $LOCAL_ENV_FILE"
    sanitize_db_summary "${DATABASE_URL:-${POSTGRES_URL:-}}"
    wait_for_database "${DATABASE_URL:-${POSTGRES_URL:-}}" "local env"
    return 0
  fi

  if docker_compose_available; then
    docker_up
    return 0
  fi

  if homebrew_up; then
    return 0
  fi

  cat >&2 <<EOF
requirement failed: no supported local Postgres provisioning path was available.
fix:
  Docker: install/start Docker, then run make run-recover-prove-local-provision
  macOS/Homebrew: brew install postgresql@16 && make run-recover-prove-local-provision
  manual: export DATABASE_URL for an existing local database, then run make run-recover-prove-local-migrate
EOF
  exit 1
}

run_migrate_and_doctor() {
  echo "[local-db] applying Overture migrations"
  make -C "$ROOT_DIR" run-recover-prove-local-migrate
  echo "[local-db] running doctor"
  make -C "$ROOT_DIR" run-recover-prove-local-doctor
}

docker_down() {
  if docker_compose_available; then
    if [[ -f "$LOCAL_ENV_FILE" ]]; then
      "${DOCKER_COMPOSE_CMD[@]}" --env-file "$LOCAL_ENV_FILE" -f "$COMPOSE_FILE" down
    else
      env POSTGRES_PASSWORD=unused "${DOCKER_COMPOSE_CMD[@]}" -f "$COMPOSE_FILE" down
    fi
  else
    echo "[local-db] Docker Compose is unavailable; nothing to stop"
  fi
}

docker_reset() {
  echo "[local-db] destructive reset requested: deleting Docker-managed local Postgres data"
  if docker_compose_available; then
    if [[ -f "$LOCAL_ENV_FILE" ]]; then
      "${DOCKER_COMPOSE_CMD[@]}" --env-file "$LOCAL_ENV_FILE" -f "$COMPOSE_FILE" down -v
    else
      env POSTGRES_PASSWORD=unused "${DOCKER_COMPOSE_CMD[@]}" -f "$COMPOSE_FILE" down -v
    fi
  else
    echo "[local-db] Docker Compose is unavailable; no Docker volume was removed"
  fi
  rm -f "$LOCAL_ENV_FILE"
  echo "[local-db] removed $LOCAL_ENV_FILE"
}

if [[ "$MODE" == "down" ]]; then
  docker_down
  exit 0
fi

if [[ "$MODE" == "reset" ]]; then
  docker_reset
  exit 0
fi

provision_up
run_migrate_and_doctor

if [[ "$MODE" == "run" ]]; then
  echo "[local-db] running full live Run / Recover / Prove demo"
  make -C "$ROOT_DIR" run-recover-prove-local
else
  echo "[local-db] local provisioning is ready"
fi

echo "[local-db] provisioning path used: $PROVISION_PATH"
