// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a stub file for development - replace with actual proto generation

package proto

import (
	"context"

	"google.golang.org/grpc"
)

// MLServiceClient is the client API for MLService service.
type MLServiceClient interface {
	Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type mlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMLServiceClient(cc grpc.ClientConnInterface) MLServiceClient {
	return &mlServiceClient{cc}
}

func (c *mlServiceClient) Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error) {
	out := new(PredictResponse)
	err := c.cc.Invoke(ctx, "/ml.MLService/Predict", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mlServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/ml.MLService/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Messages
type PredictRequest struct {
	Features []float64 `protobuf:"fixed64,1,rep,packed,name=features,proto3" json:"features,omitempty"`
	ModelId  string    `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
}

type PredictResponse struct {
	Prediction      float64 `protobuf:"fixed64,1,opt,name=prediction,proto3" json:"prediction,omitempty"`
	Confidence      float64 `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ModelId         string  `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	InferenceTimeMs float64 `protobuf:"fixed64,4,opt,name=inference_time_ms,json=inferenceTimeMs,proto3" json:"inference_time_ms,omitempty"`
}

type HealthCheckRequest struct{}

type HealthCheckResponse struct {
	Status  string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
}

// Reset, String, and ProtoMessage methods for protobuf compatibility
func (x *PredictRequest) Reset()         {}
func (x *PredictRequest) String() string { return "" }
func (x *PredictRequest) ProtoMessage()  {}

func (x *PredictResponse) Reset()         {}
func (x *PredictResponse) String() string { return "" }
func (x *PredictResponse) ProtoMessage()  {}

func (x *HealthCheckRequest) Reset()         {}
func (x *HealthCheckRequest) String() string { return "" }
func (x *HealthCheckRequest) ProtoMessage()  {}

func (x *HealthCheckResponse) Reset()         {}
func (x *HealthCheckResponse) String() string { return "" }
func (x *HealthCheckResponse) ProtoMessage()  {}

// MLServiceServer is the server API for MLService service.
type MLServiceServer interface {
	Predict(context.Context, *PredictRequest) (*PredictResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
}

// UnimplementedMLServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMLServiceServer struct{}

func (UnimplementedMLServiceServer) Predict(context.Context, *PredictRequest) (*PredictResponse, error) {
	return nil, grpc.ErrServerNotImplemented
}

func (UnimplementedMLServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, grpc.ErrServerNotImplemented
}

// RegisterMLServiceServer registers the server implementation
func RegisterMLServiceServer(s *grpc.Server, srv MLServiceServer) {
	// Stub implementation - would be generated by protoc
}
