use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderConfig {
    pub id: String,
    pub name: String,
    pub endpoint: String,
    pub model: String,
    pub api_key_env: Option<String>,
    pub cost_per_1k_input: f64,
    pub cost_per_1k_output: f64,
    pub capabilities: Vec<String>,
}

pub fn get_default_providers() -> Vec<ProviderConfig> {
    vec![
        // Tier 1: High performance
        ProviderConfig {
            id: "openai-gpt4".to_string(),
            name: "OpenAI GPT-4 Turbo".to_string(),
            endpoint: "https://api.openai.com/v1".to_string(),
            model: "gpt-4-turbo-preview".to_string(),
            api_key_env: Some("OPENAI_API_KEY".to_string()),
            cost_per_1k_input: 0.01,
            cost_per_1k_output: 0.03,
            capabilities: vec!["reasoning".into(), "coding".into()],
        },
        ProviderConfig {
            id: "anthropic-sonnet".to_string(),
            name: "Claude 3.5 Sonnet".to_string(),
            endpoint: "https://api.anthropic.com/v1".to_string(),
            model: "claude-3-5-sonnet-20241022".to_string(),
            api_key_env: Some("ANTHROPIC_API_KEY".to_string()),
            cost_per_1k_input: 0.003,
            cost_per_1k_output: 0.015,
            capabilities: vec!["reasoning".into(), "coding".into(), "long_context".into()],
        },
        ProviderConfig {
            id: "anthropic-opus".to_string(),
            name: "Claude 3 Opus".to_string(),
            endpoint: "https://api.anthropic.com/v1".to_string(),
            model: "claude-3-opus-20240229".to_string(),
            api_key_env: Some("ANTHROPIC_API_KEY".to_string()),
            cost_per_1k_input: 0.015,
            cost_per_1k_output: 0.075,
            capabilities: vec!["reasoning".into(), "coding".into()],
        },
        // Tier 2: Cost-effective
        ProviderConfig {
            id: "anthropic-haiku".to_string(),
            name: "Claude 3 Haiku".to_string(),
            endpoint: "https://api.anthropic.com/v1".to_string(),
            model: "claude-3-haiku-20240307".to_string(),
            api_key_env: Some("ANTHROPIC_API_KEY".to_string()),
            cost_per_1k_input: 0.00025,
            cost_per_1k_output: 0.00125,
            capabilities: vec!["fast".into(), "cost_effective".into()],
        },
        ProviderConfig {
            id: "groq-llama70b".to_string(),
            name: "Groq Llama 3 70B".to_string(),
            endpoint: "https://api.groq.com/openai/v1".to_string(),
            model: "llama3-70b-8192".to_string(),
            api_key_env: Some("GROQ_API_KEY".to_string()),
            cost_per_1k_input: 0.0007,
            cost_per_1k_output: 0.0008,
            capabilities: vec!["fast".into(), "coding".into()],
        },
        ProviderConfig {
            id: "groq-mixtral".to_string(),
            name: "Groq Mixtral 8x7B".to_string(),
            endpoint: "https://api.groq.com/openai/v1".to_string(),
            model: "mixtral-8x7b-32768".to_string(),
            api_key_env: Some("GROQ_API_KEY".to_string()),
            cost_per_1k_input: 0.0006,
            cost_per_1k_output: 0.0006,
            capabilities: vec!["fast".into()],
        },
        // Tier 3: Specialized
        ProviderConfig {
            id: "xai-grok".to_string(),
            name: "xAI Grok-2".to_string(),
            endpoint: "https://api.x.ai/v1".to_string(),
            model: "grok-2-latest".to_string(),
            api_key_env: Some("XAI_API_KEY".to_string()),
            cost_per_1k_input: 0.002,
            cost_per_1k_output: 0.01,
            capabilities: vec!["reasoning".into()],
        },
        ProviderConfig {
            id: "deepseek-v3".to_string(),
            name: "Deepseek V3".to_string(),
            endpoint: "https://api.deepseek.com/v1".to_string(),
            model: "deepseek-chat".to_string(),
            api_key_env: Some("DEEPSEEK_API_KEY".to_string()),
            cost_per_1k_input: 0.0014,
            cost_per_1k_output: 0.0028,
            capabilities: vec!["coding".into(), "cost_effective".into()],
        },
        // Tier 4: Google Gemini
        ProviderConfig {
            id: "google-gemini-pro".to_string(),
            name: "Google Gemini 1.5 Pro".to_string(),
            endpoint: "https://generativelanguage.googleapis.com/v1".to_string(),
            model: "gemini-1.5-pro-latest".to_string(),
            api_key_env: Some("GOOGLE_API_KEY".to_string()),
            cost_per_1k_input: 0.0035,
            cost_per_1k_output: 0.0105,
            capabilities: vec!["reasoning".into(), "long_context".into()],
        },
        ProviderConfig {
            id: "google-gemini-flash".to_string(),
            name: "Google Gemini 1.5 Flash".to_string(),
            endpoint: "https://generativelanguage.googleapis.com/v1".to_string(),
            model: "gemini-1.5-flash-latest".to_string(),
            api_key_env: Some("GOOGLE_API_KEY".to_string()),
            cost_per_1k_input: 0.00035,
            cost_per_1k_output: 0.00105,
            capabilities: vec!["fast".into(), "cost_effective".into()],
        },
        // Tier 5: Mistral AI
        ProviderConfig {
            id: "mistral-large".to_string(),
            name: "Mistral Large".to_string(),
            endpoint: "https://api.mistral.ai/v1".to_string(),
            model: "mistral-large-latest".to_string(),
            api_key_env: Some("MISTRAL_API_KEY".to_string()),
            cost_per_1k_input: 0.004,
            cost_per_1k_output: 0.012,
            capabilities: vec!["reasoning".into(), "coding".into()],
        },
        ProviderConfig {
            id: "mistral-medium".to_string(),
            name: "Mistral Medium".to_string(),
            endpoint: "https://api.mistral.ai/v1".to_string(),
            model: "mistral-medium-latest".to_string(),
            api_key_env: Some("MISTRAL_API_KEY".to_string()),
            cost_per_1k_input: 0.0027,
            cost_per_1k_output: 0.0081,
            capabilities: vec!["reasoning".into()],
        },
        ProviderConfig {
            id: "mistral-small".to_string(),
            name: "Mistral Small".to_string(),
            endpoint: "https://api.mistral.ai/v1".to_string(),
            model: "mistral-small-latest".to_string(),
            api_key_env: Some("MISTRAL_API_KEY".to_string()),
            cost_per_1k_input: 0.0006,
            cost_per_1k_output: 0.0018,
            capabilities: vec!["fast".into(), "cost_effective".into()],
        },
        // Tier 6: Cohere
        ProviderConfig {
            id: "cohere-command-r-plus".to_string(),
            name: "Cohere Command R+".to_string(),
            endpoint: "https://api.cohere.ai/v1".to_string(),
            model: "command-r-plus".to_string(),
            api_key_env: Some("COHERE_API_KEY".to_string()),
            cost_per_1k_input: 0.003,
            cost_per_1k_output: 0.015,
            capabilities: vec!["reasoning".into(), "rag".into()],
        },
        ProviderConfig {
            id: "cohere-command-r".to_string(),
            name: "Cohere Command R".to_string(),
            endpoint: "https://api.cohere.ai/v1".to_string(),
            model: "command-r".to_string(),
            api_key_env: Some("COHERE_API_KEY".to_string()),
            cost_per_1k_input: 0.0005,
            cost_per_1k_output: 0.0015,
            capabilities: vec!["rag".into(), "cost_effective".into()],
        },
        // Tier 7: Together AI
        ProviderConfig {
            id: "together-llama3-70b".to_string(),
            name: "Together Llama 3 70B".to_string(),
            endpoint: "https://api.together.xyz/v1".to_string(),
            model: "meta-llama/Llama-3-70b-chat-hf".to_string(),
            api_key_env: Some("TOGETHER_API_KEY".to_string()),
            cost_per_1k_input: 0.0009,
            cost_per_1k_output: 0.0009,
            capabilities: vec!["coding".into(), "cost_effective".into()],
        },
        ProviderConfig {
            id: "together-mixtral-8x22b".to_string(),
            name: "Together Mixtral 8x22B".to_string(),
            endpoint: "https://api.together.xyz/v1".to_string(),
            model: "mistralai/Mixtral-8x22B-Instruct-v0.1".to_string(),
            api_key_env: Some("TOGETHER_API_KEY".to_string()),
            cost_per_1k_input: 0.0012,
            cost_per_1k_output: 0.0012,
            capabilities: vec!["reasoning".into()],
        },
        // Tier 8: Perplexity
        ProviderConfig {
            id: "perplexity-llama-70b-online".to_string(),
            name: "Perplexity Llama 70B Online".to_string(),
            endpoint: "https://api.perplexity.ai/v1".to_string(),
            model: "llama-3-sonar-large-32k-online".to_string(),
            api_key_env: Some("PERPLEXITY_API_KEY".to_string()),
            cost_per_1k_input: 0.001,
            cost_per_1k_output: 0.001,
            capabilities: vec!["search".into(), "realtime".into()],
        },
        ProviderConfig {
            id: "perplexity-llama-8b-online".to_string(),
            name: "Perplexity Llama 8B Online".to_string(),
            endpoint: "https://api.perplexity.ai/v1".to_string(),
            model: "llama-3-sonar-small-32k-online".to_string(),
            api_key_env: Some("PERPLEXITY_API_KEY".to_string()),
            cost_per_1k_input: 0.0002,
            cost_per_1k_output: 0.0002,
            capabilities: vec!["search".into(), "fast".into(), "cost_effective".into()],
        },
        // Tier 9: Fireworks AI
        ProviderConfig {
            id: "fireworks-llama3-70b".to_string(),
            name: "Fireworks Llama 3 70B".to_string(),
            endpoint: "https://api.fireworks.ai/inference/v1".to_string(),
            model: "accounts/fireworks/models/llama-v3-70b-instruct".to_string(),
            api_key_env: Some("FIREWORKS_API_KEY".to_string()),
            cost_per_1k_input: 0.0009,
            cost_per_1k_output: 0.0009,
            capabilities: vec!["fast".into(), "coding".into()],
        },
        ProviderConfig {
            id: "fireworks-mixtral-8x7b".to_string(),
            name: "Fireworks Mixtral 8x7B".to_string(),
            endpoint: "https://api.fireworks.ai/inference/v1".to_string(),
            model: "accounts/fireworks/models/mixtral-8x7b-instruct".to_string(),
            api_key_env: Some("FIREWORKS_API_KEY".to_string()),
            cost_per_1k_input: 0.0005,
            cost_per_1k_output: 0.0005,
            capabilities: vec!["fast".into(), "cost_effective".into()],
        },
        // Tier 10: Anyscale
        ProviderConfig {
            id: "anyscale-llama3-70b".to_string(),
            name: "Anyscale Llama 3 70B".to_string(),
            endpoint: "https://api.endpoints.anyscale.com/v1".to_string(),
            model: "meta-llama/Meta-Llama-3-70B-Instruct".to_string(),
            api_key_env: Some("ANYSCALE_API_KEY".to_string()),
            cost_per_1k_input: 0.001,
            cost_per_1k_output: 0.001,
            capabilities: vec!["coding".into()],
        },
        ProviderConfig {
            id: "anyscale-mixtral-8x7b".to_string(),
            name: "Anyscale Mixtral 8x7B".to_string(),
            endpoint: "https://api.endpoints.anyscale.com/v1".to_string(),
            model: "mistralai/Mixtral-8x7B-Instruct-v0.1".to_string(),
            api_key_env: Some("ANYSCALE_API_KEY".to_string()),
            cost_per_1k_input: 0.0005,
            cost_per_1k_output: 0.0005,
            capabilities: vec!["fast".into()],
        },
        // Tier 11: More OpenAI models
        ProviderConfig {
            id: "openai-gpt35-turbo".to_string(),
            name: "OpenAI GPT-3.5 Turbo".to_string(),
            endpoint: "https://api.openai.com/v1".to_string(),
            model: "gpt-3.5-turbo".to_string(),
            api_key_env: Some("OPENAI_API_KEY".to_string()),
            cost_per_1k_input: 0.0005,
            cost_per_1k_output: 0.0015,
            capabilities: vec!["fast".into(), "cost_effective".into()],
        },
        ProviderConfig {
            id: "openai-gpt4o".to_string(),
            name: "OpenAI GPT-4o".to_string(),
            endpoint: "https://api.openai.com/v1".to_string(),
            model: "gpt-4o".to_string(),
            api_key_env: Some("OPENAI_API_KEY".to_string()),
            cost_per_1k_input: 0.005,
            cost_per_1k_output: 0.015,
            capabilities: vec!["reasoning".into(), "multimodal".into()],
        },
        ProviderConfig {
            id: "openai-gpt4o-mini".to_string(),
            name: "OpenAI GPT-4o Mini".to_string(),
            endpoint: "https://api.openai.com/v1".to_string(),
            model: "gpt-4o-mini".to_string(),
            api_key_env: Some("OPENAI_API_KEY".to_string()),
            cost_per_1k_input: 0.00015,
            cost_per_1k_output: 0.0006,
            capabilities: vec!["fast".into(), "cost_effective".into()],
        },
        // Tier 12: More Groq models
        ProviderConfig {
            id: "groq-llama3-8b".to_string(),
            name: "Groq Llama 3 8B".to_string(),
            endpoint: "https://api.groq.com/openai/v1".to_string(),
            model: "llama3-8b-8192".to_string(),
            api_key_env: Some("GROQ_API_KEY".to_string()),
            cost_per_1k_input: 0.0001,
            cost_per_1k_output: 0.0001,
            capabilities: vec!["fast".into(), "cost_effective".into()],
        },
        ProviderConfig {
            id: "groq-gemma-7b".to_string(),
            name: "Groq Gemma 7B".to_string(),
            endpoint: "https://api.groq.com/openai/v1".to_string(),
            model: "gemma-7b-it".to_string(),
            api_key_env: Some("GROQ_API_KEY".to_string()),
            cost_per_1k_input: 0.0001,
            cost_per_1k_output: 0.0001,
            capabilities: vec!["fast".into(), "cost_effective".into()],
        },
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_providers() {
        let providers = get_default_providers();
        assert!(!providers.is_empty());
        assert!(providers.iter().any(|p| p.id == "openai-gpt4"));
        assert!(providers.iter().any(|p| p.id == "anthropic-sonnet"));
    }
}
