[package]
name = "igris-recovery"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dependencies.igris-ros2]
path = "../igris-ros2"
optional = true

[features]
default = []
ros2 = ["dep:igris-ros2", "igris-ros2/ros2"]
